In [2]:
import numpy as np
from sklearn.model_selection import train_test_split

In [13]:
X = np.arange(0,100).reshape(10,10)
y = np.arange(10)
X.shape

(10, 10)

In [34]:
train_test_split?

In [14]:
train_test_split(X, y, test_size=.2)

[array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]]),
 array([[70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]),
 array([5, 6, 0, 1, 2, 8, 4, 3]),
 array([7, 9])]

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2)

In [30]:
X_train, y_train

(array([[80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]]),
 array([8, 1, 7, 6, 5, 4, 2, 3]))

In [31]:
X_test, y_test

(array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]),
 array([0, 9]))