In [3]:
!dir

 Volume in Laufwerk C: hat keine Bezeichnung.
 Volumeseriennummer: 7C80-4064

 Verzeichnis von C:\Users\jensm\Desktop\local\copyandpaste\Mathematics\LinearAlgebra

06/22/2023  07:20 PM    <DIR>          .
06/17/2023  01:16 AM    <DIR>          ..
06/22/2023  07:07 PM    <DIR>          .ipynb_checkpoints
04/30/2023  03:33 PM            23,175 dot_product.ipynb
04/30/2023  03:33 PM           823,895 euclideandistance.ipynb
06/22/2023  07:20 PM            11,985 ipython and shell.ipynb
05/17/2023  03:58 PM           326,693 Linear transformation.ipynb
06/13/2023  05:01 PM             2,251 row echolon.ipynb
06/22/2023  07:02 PM           320,183 sys_of_lin_eq.ipynb
               6 Datei(en),      1,508,182 Bytes
               3 Verzeichnis(se), 10,735,611,904 Bytes frei


In [4]:
%pwd

'C:\\Users\\jensm\\Desktop\\local\\copyandpaste\\Mathematics\\LinearAlgebra'

In [5]:
prompt_output = !echo hello world

In [6]:
prompt_output

['hello world']

In [7]:
dir_ = !dir
dir_[3]

' Verzeichnis von C:\\Users\\jensm\\Desktop\\local\\copyandpaste\\Mathematics\\LinearAlgebra'

In [8]:
!dir

 Volume in Laufwerk C: hat keine Bezeichnung.
 Volumeseriennummer: 7C80-4064

 Verzeichnis von C:\Users\jensm\Desktop\local\copyandpaste\Mathematics\LinearAlgebra

06/22/2023  07:20 PM    <DIR>          .
06/17/2023  01:16 AM    <DIR>          ..
06/22/2023  07:07 PM    <DIR>          .ipynb_checkpoints
04/30/2023  03:33 PM            23,175 dot_product.ipynb
04/30/2023  03:33 PM           823,895 euclideandistance.ipynb
06/22/2023  07:20 PM            11,985 ipython and shell.ipynb
05/17/2023  03:58 PM           326,693 Linear transformation.ipynb
06/13/2023  05:01 PM             2,251 row echolon.ipynb
06/22/2023  07:02 PM           320,183 sys_of_lin_eq.ipynb
               6 Datei(en),      1,508,182 Bytes
               3 Verzeichnis(se), 10,735,546,368 Bytes frei


In [16]:
message = 'hello from python'

In [17]:
!echo {message}

hello from python


In [18]:
type(dir_)

IPython.utils.text.SList

In [19]:
In[:10]

['',
 "get_ipython().system('dir')",
 "get_ipython().run_line_magic('pwd', '')",
 "get_ipython().system('dir')",
 "get_ipython().run_line_magic('pwd', '')",
 "prompt_output = get_ipython().getoutput('echo hello world')",
 'prompt_output',
 "dir_ = get_ipython().getoutput('dir')\ndir_[3]",
 "get_ipython().system('dir')",
 "message = 'hello from python'"]

In [25]:
Out[11]

IPython.utils.text.SList

In [26]:
%pwd

'C:\\Users\\jensm\\Desktop\\local\\copyandpaste\\Mathematics\\LinearAlgebra'

In [33]:
%cd ..

C:\Users\jensm\Desktop


In [34]:
%pwd

'C:\\Users\\jensm\\Desktop'

In [35]:
%cd local

C:\Users\jensm\Desktop\local


In [30]:
!mkdir myfolder

In [36]:
%cd myfolder

C:\Users\jensm\Desktop\local\myfolder


In [37]:
%pwd

'C:\\Users\\jensm\\Desktop\\local\\myfolder'

In [38]:
!type nul > main.py

In [89]:
!code .

In [39]:
%run main.py

hello world


In [40]:
cd ..

C:\Users\jensm\Desktop\local


In [41]:
cd myfolder

C:\Users\jensm\Desktop\local\myfolder


In [42]:
run main.py

hello world


In [1]:
In

['', 'In']

In [4]:
%xmode verbose

Exception reporting mode: Verbose


In [6]:
%history -n 1-2

   1: In
   2: %xmode verbose


In [7]:
Out

{1: ['',
  'In',
  "get_ipython().run_line_magic('xmode', 'verbose')",
  '3 / 0 ',
  "get_ipython().run_line_magic('xmode', 'verbose')",
  "get_ipython().run_line_magic('history', '-n')",
  "get_ipython().run_line_magic('history', '-n 1-2')",
  'Out']}

In [10]:
import jupyter

In [11]:
dir(jupyter)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '__version__']

In [1]:
%load_ext?

In [32]:
import numpy as np
def A(x):
    B = [x **10 for x in range(10000)]
    C = np.array(B)
    C * 20000
    return C[0]

In [33]:
%time A(20)

CPU times: total: 31.2 ms
Wall time: 34.5 ms


0

In [34]:
%prun A(20)

In [23]:
!pip install line_profiler

     -------------------------------------- 84.7/84.7 kB 318.3 kB/s eta 0:00:00



[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [25]:
%load_ext line_profiler

In [26]:
%lprun?

In [38]:
%lprun -f A A(20)

In [39]:
!pip install memory_profiler


[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [40]:
%load_ext memory_profiler

In [41]:
%memit A(50)

peak memory: 132.18 MiB, increment: 1.54 MiB


In [43]:
%%file test_module.py

import numpy as np
def test_function(x):
    B = [x **10 for x in range(10000)]
    C = np.array(B)
    C * 20000
    return C[0] 

Overwriting test_module.py


In [44]:
import test_module as m1

In [46]:
%mprun -f m1.test_function m1.test_function(2000)

In [49]:
import numpy as np
x = np.array([1,2,3])
x[np.newaxis,:]

array([[1, 2, 3]])

In [50]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [51]:
x

array([1, 2, 3])

In [55]:
x + x[:, np.newaxis]

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])