In [3]:
!dir

 Volume in Laufwerk C: hat keine Bezeichnung.
 Volumeseriennummer: A055-9EBC

 Verzeichnis von C:\Users\jensm\Desktop\local\GitHub\copyandpaste\Python_Libs\Python&IPython

07/27/2023  07:02 AM    <DIR>          .
07/20/2023  04:15 AM    <DIR>          ..
07/27/2023  06:29 AM    <DIR>          .ipynb_checkpoints
07/27/2023  06:58 AM             3,922 block structure.ipynb
06/10/2023  02:46 PM             7,743 class method, factory and dataclass.ipynb
07/27/2023  06:27 AM             3,331 closure class.ipynb
06/10/2023  02:46 PM             5,940 Decorators and function timer.ipynb
07/27/2023  07:02 AM            18,516 ipython and shell.ipynb
06/10/2023  02:46 PM             3,171 Markdown.ipynb
06/27/2023  12:45 AM               138 test_module.py
06/27/2023  12:45 AM    <DIR>          __pycache__
               7 Datei(en),         42,761 Bytes
               4 Verzeichnis(se), 215,938,125,824 Bytes frei


In [4]:
%pwd

'C:\\Users\\jensm\\Desktop\\local\\GitHub\\copyandpaste\\Python_Libs\\Python&IPython'

In [ ]:
prompt_output = !echo hello world

In [ ]:
prompt_output

In [7]:
dir_ = !dir
dir_[3]

' Verzeichnis von C:\\Users\\jensm\\Desktop\\local\\GitHub\\copyandpaste\\Python_Libs\\Python&IPython'

In [8]:
!dir

 Volume in Laufwerk C: hat keine Bezeichnung.
 Volumeseriennummer: A055-9EBC

 Verzeichnis von C:\Users\jensm\Desktop\local\GitHub\copyandpaste\Python_Libs\Python&IPython

07/27/2023  07:02 AM    <DIR>          .
07/20/2023  04:15 AM    <DIR>          ..
07/27/2023  06:29 AM    <DIR>          .ipynb_checkpoints
07/27/2023  06:58 AM             3,922 block structure.ipynb
06/10/2023  02:46 PM             7,743 class method, factory and dataclass.ipynb
07/27/2023  06:27 AM             3,331 closure class.ipynb
06/10/2023  02:46 PM             5,940 Decorators and function timer.ipynb
07/27/2023  07:02 AM            18,516 ipython and shell.ipynb
06/10/2023  02:46 PM             3,171 Markdown.ipynb
06/27/2023  12:45 AM               138 test_module.py
06/27/2023  12:45 AM    <DIR>          __pycache__
               7 Datei(en),         42,761 Bytes
               4 Verzeichnis(se), 215,938,125,824 Bytes frei


In [9]:
message = 'hello from python'

In [10]:
!echo {message}

hello from python


In [11]:
type(dir_)

IPython.utils.text.SList

In [12]:
In[:10]

['',
 "get_ipython().run_line_magic('pinfo', '%load_ext')",
 "get_ipython().run_line_magic('mprun', '-f m1.test_function m1.test_function(2000)')",
 "get_ipython().system('dir')",
 "get_ipython().run_line_magic('pwd', '')",
 "prompt_output = get_ipython().getoutput('echo hello world')",
 'prompt_output',
 "dir_ = get_ipython().getoutput('dir')\ndir_[3]",
 "get_ipython().system('dir')",
 "message = 'hello from python'"]

In [13]:
Out[11]

IPython.utils.text.SList

In [14]:
%pwd

'C:\\Users\\jensm\\Desktop\\local\\GitHub\\copyandpaste\\Python_Libs\\Python&IPython'

In [15]:
%cd ..

C:\Users\jensm\Desktop\local\GitHub\copyandpaste\Python_Libs


In [16]:
%pwd

'C:\\Users\\jensm\\Desktop\\local\\GitHub\\copyandpaste\\Python_Libs'

In [17]:
%cd local

[WinError 2] Das System kann die angegebene Datei nicht finden: 'local'
C:\Users\jensm\Desktop\local\GitHub\copyandpaste\Python_Libs


In [18]:
!mkdir myfolder

In [19]:
%cd myfolder

C:\Users\jensm\Desktop\local\GitHub\copyandpaste\Python_Libs\myfolder


In [20]:
%pwd

'C:\\Users\\jensm\\Desktop\\local\\GitHub\\copyandpaste\\Python_Libs\\myfolder'

In [21]:
!type nul > main.py

In [22]:
!code .

In [23]:
%run main.py

In [24]:
cd ..

C:\Users\jensm\Desktop\local\GitHub\copyandpaste\Python_Libs


In [25]:
cd myfolder

C:\Users\jensm\Desktop\local\GitHub\copyandpaste\Python_Libs\myfolder


In [26]:
run main.py

In [27]:
In

['',
 "get_ipython().run_line_magic('pinfo', '%load_ext')",
 "get_ipython().run_line_magic('mprun', '-f m1.test_function m1.test_function(2000)')",
 "get_ipython().system('dir')",
 "get_ipython().run_line_magic('pwd', '')",
 "prompt_output = get_ipython().getoutput('echo hello world')",
 'prompt_output',
 "dir_ = get_ipython().getoutput('dir')\ndir_[3]",
 "get_ipython().system('dir')",
 "message = 'hello from python'",
 "get_ipython().system('echo {message}')",
 'type(dir_)',
 'In[:10]',
 'Out[11]',
 "get_ipython().run_line_magic('pwd', '')",
 "get_ipython().run_line_magic('cd', '..')",
 "get_ipython().run_line_magic('pwd', '')",
 "get_ipython().run_line_magic('cd', 'local')",
 "get_ipython().system('mkdir myfolder')",
 "get_ipython().run_line_magic('cd', 'myfolder')",
 "get_ipython().run_line_magic('pwd', '')",
 "get_ipython().system('type nul > main.py')",
 "get_ipython().system('code .')",
 "get_ipython().run_line_magic('run', 'main.py')",
 "get_ipython().run_line_magic('cd', '..')"

In [28]:
%xmode verbose

Exception reporting mode: Verbose


In [29]:
%history -n 1-2

   1: %load_ext?
   2: %mprun -f m1.test_function m1.test_function(2000)


In [30]:
Out

{4: 'C:\\Users\\jensm\\Desktop\\local\\GitHub\\copyandpaste\\Python_Libs\\Python&IPython',
 6: ['hello world'],
 7: ' Verzeichnis von C:\\Users\\jensm\\Desktop\\local\\GitHub\\copyandpaste\\Python_Libs\\Python&IPython',
 11: IPython.utils.text.SList,
 12: ['',
  "get_ipython().run_line_magic('pinfo', '%load_ext')",
  "get_ipython().run_line_magic('mprun', '-f m1.test_function m1.test_function(2000)')",
  "get_ipython().system('dir')",
  "get_ipython().run_line_magic('pwd', '')",
  "prompt_output = get_ipython().getoutput('echo hello world')",
  'prompt_output',
  "dir_ = get_ipython().getoutput('dir')\ndir_[3]",
  "get_ipython().system('dir')",
  "message = 'hello from python'"],
 13: IPython.utils.text.SList,
 14: 'C:\\Users\\jensm\\Desktop\\local\\GitHub\\copyandpaste\\Python_Libs\\Python&IPython',
 16: 'C:\\Users\\jensm\\Desktop\\local\\GitHub\\copyandpaste\\Python_Libs',
 20: 'C:\\Users\\jensm\\Desktop\\local\\GitHub\\copyandpaste\\Python_Libs\\myfolder',
 27: ['',
  "get_ipython()

In [31]:
import jupyter

In [32]:
dir(jupyter)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__']

In [33]:
%load_ext?

In [34]:
import numpy as np
def A(x):
    B = [x **10 for x in range(10000)]
    C = np.array(B)
    C * 20000
    return C[0]

In [35]:
%time A(20)

CPU times: total: 0 ns
Wall time: 3 ms


0

In [36]:
%prun A(20)

In [37]:
!pip install line_profiler


[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip



                                              0.0/84.7 kB ? eta -:--:--
     ----                                     10.2/84.7 kB ? eta -:--:--
     ----                                     10.2/84.7 kB ? eta -:--:--
     -------------                          30.7/84.7 kB 187.9 kB/s eta 0:00:01
     ---------------------------            61.4/84.7 kB 297.7 kB/s eta 0:00:01
     --------------------------------       71.7/84.7 kB 328.6 kB/s eta 0:00:01
     -------------------------------------- 84.7/84.7 kB 297.9 kB/s eta 0:00:00


In [38]:
%load_ext line_profiler

In [39]:
%lprun?

In [40]:
%lprun -f A A(20)

In [41]:
!pip install memory_profiler


[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [42]:
%load_ext memory_profiler

In [43]:
%memit A(50)

peak memory: 91.27 MiB, increment: 1.58 MiB


In [44]:
%%file test_module.py

import numpy as np
def test_function(x):
    B = [x **10 for x in range(10000)]
    C = np.array(B)
    C * 20000
    return C[0] 

Writing test_module.py


In [45]:
import test_module as m1

In [46]:
%mprun -f m1.test_function m1.test_function(2000)

In [47]:
import numpy as np
x = np.array([1,2,3])
x[np.newaxis,:]

array([[1, 2, 3]])

In [48]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [49]:
x

array([1, 2, 3])

In [50]:
x + x[:, np.newaxis]

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])