In [23]:
import numpy as np

In [24]:
rg = np.random.default_rng(4)
rg.random((2,3))

array([[0.94305611, 0.51132755, 0.97624371],
       [0.08083602, 0.60735583, 0.37648658]])

In [25]:
L = np.arange(12).reshape(3,4)
L

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
print(L.sum())
print(L.cumsum())

66
[ 0  1  3  6 10 15 21 28 36 45 55 66]


In [27]:
L.sum(axis=1), L.sum(axis=0)

(array([ 6, 22, 38]), array([12, 15, 18, 21]))

In [28]:
L.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

In [29]:
L.cumsum(axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]], dtype=int32)

In [30]:
A = np.arange(24).reshape((2,2,3,2))
A[0,0].size

6

In [31]:
A[1,0,1] = 0
A

array([[[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]]],


       [[[12, 13],
         [ 0,  0],
         [16, 17]],

        [[18, 19],
         [20, 21],
         [22, 23]]]])

In [32]:
A[...,1]

array([[[ 1,  3,  5],
        [ 7,  9, 11]],

       [[13,  0, 17],
        [19, 21, 23]]])

In [33]:
D = np.arange(288).reshape(2,3,2,6,4)
D[0,...,1,1]

array([[  5,  29],
       [ 53,  77],
       [101, 125]])

In [34]:
D[0]

array([[[[  0,   1,   2,   3],
         [  4,   5,   6,   7],
         [  8,   9,  10,  11],
         [ 12,  13,  14,  15],
         [ 16,  17,  18,  19],
         [ 20,  21,  22,  23]],

        [[ 24,  25,  26,  27],
         [ 28,  29,  30,  31],
         [ 32,  33,  34,  35],
         [ 36,  37,  38,  39],
         [ 40,  41,  42,  43],
         [ 44,  45,  46,  47]]],


       [[[ 48,  49,  50,  51],
         [ 52,  53,  54,  55],
         [ 56,  57,  58,  59],
         [ 60,  61,  62,  63],
         [ 64,  65,  66,  67],
         [ 68,  69,  70,  71]],

        [[ 72,  73,  74,  75],
         [ 76,  77,  78,  79],
         [ 80,  81,  82,  83],
         [ 84,  85,  86,  87],
         [ 88,  89,  90,  91],
         [ 92,  93,  94,  95]]],


       [[[ 96,  97,  98,  99],
         [100, 101, 102, 103],
         [104, 105, 106, 107],
         [108, 109, 110, 111],
         [112, 113, 114, 115],
         [116, 117, 118, 119]],

        [[120, 121, 122, 123],
         [124, 125, 126, 

In [36]:
A = np.arange(36).reshape((3,3,4))
A

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [37]:
A[0,0,:]

array([0, 1, 2, 3])