In [51]:
import torch
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('dark_background')

In [52]:
torch.__version__

'2.1.0+cpu'

In [53]:
np.array([10])

array([10])

In [54]:
x = torch.tensor([2.0], requires_grad=True)
y = torch.sin(x)
y.backward()  # Computes gradients
#print(x.grad) 

In [55]:
torch.cos(x).backward()

In [56]:
dump = lambda x, c: (x,c)

In [57]:
dump(**{'x':3,'c': 4})

(3, 4)

In [58]:
f = lambda x: 3*x**2 - 4*x

In [59]:
for h in 10**np.arange(-1,-6, -1, dtype=float):
    print(f'h={h:.5f}, numerical limit= {(f(1+h) - f(1)) / h:.5f}')

h=0.10000, numerical limit= 2.30000
h=0.01000, numerical limit= 2.03000
h=0.00100, numerical limit= 2.00300
h=0.00010, numerical limit= 2.00030
h=0.00001, numerical limit= 2.00003


In [60]:
x = torch.arange(4.0, requires_grad=True)
y = 2 * x @ x
y.backward()
dy_dx = x.grad
y, dy_dx

(tensor(28., grad_fn=<DotBackward0>), tensor([ 0.,  4.,  8., 12.]))

In [61]:
x.grad == 4*x

tensor([True, True, True, True])

In [62]:
x.grad.zero_()
y = 2 * x.sum()
y.backward()
x.grad

tensor([2., 2., 2., 2.])

In [63]:
y

tensor(12., grad_fn=<MulBackward0>)

In [64]:
x.sum()

tensor(6., grad_fn=<SumBackward0>)

Invoking backward on a non-scalar elicits an error unless we tell PyTorch how to reduce the object to a scalar. More formally, we need to provide some vector 
 such that backward will compute $\mathbf{v}^\top \partial_{\mathbf{x}} \mathbf{y}$
 rather than $\partial_{\mathbf{x}} \mathbf{y}$


In [65]:
x.grad.zero_()
y = x*x
y.backward(gradient=torch.ones(len(y))) #gradient representing v
x.grad

tensor([0., 2., 4., 6.])

In [66]:
y

tensor([0., 1., 4., 9.], grad_fn=<MulBackward0>)

In [67]:
x.grad.zero_()
y = x*x
u = y.detach()
z = u * x

out = z.sum()
out.backward()

x.grad == u

tensor([True, True, True, True])

In [75]:
x = torch.randn(4, 4)
y = x.view(16)
y.shape, x.shape

(torch.Size([16]), torch.Size([4, 4]))

In [1]:
3*.6**2*.4

0.43200000000000005

In [2]:
from math import log

In [8]:
log(32)

3.4657359027997265

In [11]:
log(16, 2)

4.0

In [27]:
log_2 = lambda x: log(x, 2)

In [28]:
log_2(8*2) == log_2(2) + log_2(8)

True

In [29]:
log_2(16/2) == log_2(16) - log_2(2)

True

In [30]:
log_2(16**3) == 3 * log_2(16)

True

In [31]:
log_2(1/2**3) == -log_2(2**3)

True