In [35]:
import torch
from torch import Tensor as T

In [36]:
type(torch.ones(3))

torch.Tensor

In [37]:
T([1,2,3,4]).reshape(2,2)

tensor([[1., 2.],
        [3., 4.]])

In [38]:
torch.tan(T([torch.pi/4]))

tensor([1.])

In [39]:
from torchvision import models
from torchvision import transforms

In [40]:
#dir(models)

In [41]:
#alexnet = models.AlexNet()
resnet = models.resnet101(pretrained=True)

C:\Users\jensm\AppData\Local\Programs\Python\Python311\Lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
C:\Users\jensm\AppData\Local\Programs\Python\Python311\Lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet101_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet101_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


In [42]:
resnet

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (downsample): Sequential(
        (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 

In [43]:
preprocess = transforms.Compose([
transforms.Resize(256),
transforms.CenterCrop(224),
transforms.ToTensor(),
transforms.Normalize(
mean=[0.485, 0.456, 0.406],
std=[0.229, 0.224, 0.225]
)])

In [44]:
import matplotlib.pyplot as plt
from PIL import Image

In [45]:
%ls

 Volume in Laufwerk C: hat keine Bezeichnung.
 Volumeseriennummer: A055-9EBC

 Verzeichnis von C:\Users\jensm\Desktop\local\GitHub\copyandpaste\Python_Libs\pytorch

08/01/2023  11:53 AM    <DIR>          .
07/31/2023  06:23 AM    <DIR>          ..
08/01/2023  11:53 AM    <DIR>          .ipynb_checkpoints
07/28/2023  06:30 PM            21,675 imagenet-classes.txt
08/01/2023  11:34 AM            37,075 pretrained_network.ipynb
08/01/2023  11:53 AM            37,392 pretrained_network2.ipynb
08/01/2023  11:41 AM            37,152 pretrained_network-Copy1.ipynb
07/28/2023  06:18 PM           264,625 tiger.jpeg
08/01/2023  11:50 AM           185,788 Unbenannt.jpg
07/28/2023  06:13 PM           144,658 unidentified_creature.jpg
               7 Datei(en),        728,365 Bytes
               3 Verzeichnis(se), 207,555,416,064 Bytes frei


In [46]:
tiger = Image.open('unbenannt.jpg')
tiger.show()

In [47]:
tiger_proc = preprocess(tiger)
tiger_proc

tensor([[[ 1.4098,  1.3755,  1.3584,  ..., -0.8849, -0.9705, -0.9877],
         [ 1.3927,  1.3755,  1.3413,  ..., -0.9534, -1.0390, -1.0733],
         [ 1.3755,  1.3584,  1.3242,  ..., -1.1932, -1.2617, -1.3130],
         ...,
         [ 1.5297,  1.5297,  1.5297,  ..., -0.5424, -0.5767, -0.1486],
         [ 1.5468,  1.5297,  1.5297,  ..., -0.5253, -0.4397,  0.0569],
         [ 1.5639,  1.5639,  1.5639,  ..., -0.4568, -0.1828,  0.1597]],

        [[ 1.5707,  1.5182,  1.5007,  ..., -0.6527, -0.7052, -0.7227],
         [ 1.5357,  1.5182,  1.4832,  ..., -0.6877, -0.7577, -0.7927],
         [ 1.5182,  1.5007,  1.4832,  ..., -0.9153, -0.9678, -1.0028],
         ...,
         [ 1.7633,  1.7458,  1.7458,  ..., -0.7227, -0.7052, -0.1975],
         [ 1.7633,  1.7633,  1.7633,  ..., -0.7052, -0.5651,  0.0301],
         [ 1.7983,  1.7983,  1.7983,  ..., -0.6001, -0.2675,  0.1702]],

        [[ 1.7511,  1.6988,  1.6814,  ..., -0.5495, -0.6018, -0.6018],
         [ 1.7163,  1.6988,  1.6640,  ..., -0

In [48]:
batch_t = torch.unsqueeze(tiger_proc, 0)
batch_t

tensor([[[[ 1.4098,  1.3755,  1.3584,  ..., -0.8849, -0.9705, -0.9877],
          [ 1.3927,  1.3755,  1.3413,  ..., -0.9534, -1.0390, -1.0733],
          [ 1.3755,  1.3584,  1.3242,  ..., -1.1932, -1.2617, -1.3130],
          ...,
          [ 1.5297,  1.5297,  1.5297,  ..., -0.5424, -0.5767, -0.1486],
          [ 1.5468,  1.5297,  1.5297,  ..., -0.5253, -0.4397,  0.0569],
          [ 1.5639,  1.5639,  1.5639,  ..., -0.4568, -0.1828,  0.1597]],

         [[ 1.5707,  1.5182,  1.5007,  ..., -0.6527, -0.7052, -0.7227],
          [ 1.5357,  1.5182,  1.4832,  ..., -0.6877, -0.7577, -0.7927],
          [ 1.5182,  1.5007,  1.4832,  ..., -0.9153, -0.9678, -1.0028],
          ...,
          [ 1.7633,  1.7458,  1.7458,  ..., -0.7227, -0.7052, -0.1975],
          [ 1.7633,  1.7633,  1.7633,  ..., -0.7052, -0.5651,  0.0301],
          [ 1.7983,  1.7983,  1.7983,  ..., -0.6001, -0.2675,  0.1702]],

         [[ 1.7511,  1.6988,  1.6814,  ..., -0.5495, -0.6018, -0.6018],
          [ 1.7163,  1.6988,  

In [49]:
#put the model in eval mode
resnet.eval();

In [50]:
#give him the picture(s)
out = resnet(batch_t)
out.shape

torch.Size([1, 1000])

In [51]:
#the output is a probability distribution over the imagenet-classes labels
with open('imagenet-classes.txt') as f:
    labels = [line.strip() for line in f.readlines()]

In [52]:
out.sort(descending=True);

In [53]:
_, index = torch.max(out, 1)

In [59]:
out

tensor([[-1.7485e+00, -4.0977e-01, -2.8298e+00, -4.1633e+00, -2.3232e+00,
         -1.8247e+00, -2.6038e+00,  5.7978e-01, -1.7759e+00, -2.1941e+00,
         -2.4747e+00, -1.0304e+00, -3.7757e-01,  5.7358e-01, -1.0502e-01,
         -2.2922e+00, -2.8999e-01, -8.0838e-01, -1.0661e+00,  7.0045e-01,
         -2.6556e+00, -1.5911e+00, -7.6794e-01,  2.0383e-01, -1.2600e+00,
         -2.7303e+00, -1.9038e+00,  1.6126e-01, -6.6457e-01, -1.5973e+00,
         -2.4024e+00, -2.1402e+00, -3.8955e-01, -2.1335e+00, -2.2686e+00,
         -2.0827e+00, -4.2256e-02, -1.4172e+00, -3.1261e+00, -2.6239e+00,
         -1.6103e+00, -2.4880e+00, -2.4561e+00, -2.0080e+00, -1.4477e+00,
         -2.3215e+00, -1.5793e+00, -3.9863e-01, -3.5998e+00, -4.0766e+00,
         -3.8947e+00, -1.1846e+00,  1.0536e+00,  2.2693e-01,  1.4281e-01,
         -1.0405e+00, -1.1934e+00, -1.1024e+00, -3.8516e+00, -7.3700e-01,
         -1.1417e-01, -8.5054e-01, -3.6421e+00, -3.2094e+00, -2.5219e+00,
         -3.1783e+00, -2.2784e+00, -1.

In [54]:
percentage = torch.nn.functional.softmax(out, dim=1)[0]
labels[index[0]], percentage[index[0]]

('wig', tensor(0.9763, grad_fn=<SelectBackward0>))

In [55]:
#labels

In [56]:
_, indices = torch.sort(out, descending=True)
[(labels[idx], percentage[idx].item()) for idx in indices[0][:5]]

[('wig', 0.9762840867042542),
 ('hair spray', 0.006045321933925152),
 ('hand blower, blow dryer, blow drier, hair dryer, hair drier',
  0.004002895671874285),
 ('hair slide', 0.00277012144215405),
 ('mortarboard', 0.0017771146958693862)]