In [1]:
import torch
from torch import Tensor as T

In [2]:
type(torch.ones(3))

torch.Tensor

In [3]:
T([1,2,3,4]).reshape(2,2)

tensor([[1., 2.],
        [3., 4.]])

In [4]:
torch.tan(T([torch.pi/4]))

tensor([1.])

In [5]:
from torchvision import models
from torchvision import transforms

In [6]:
#dir(models)

In [7]:
#alexnet = models.AlexNet()
resnet = models.resnet101(pretrained=True)

C:\Users\jensm\anaconda3\Lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
C:\Users\jensm\anaconda3\Lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet101_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet101_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


In [8]:
resnet

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (downsample): Sequential(
        (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 

In [9]:
preprocess = transforms.Compose([
transforms.Resize(256),
transforms.CenterCrop(224),
transforms.ToTensor(),
transforms.Normalize(
mean=[0.485, 0.456, 0.406],
std=[0.229, 0.224, 0.225]
)])

In [10]:
import matplotlib.pyplot as plt
from PIL import Image

In [11]:
%ls

 Volume in Laufwerk C: hat keine Bezeichnung.
 Volumeseriennummer: A055-9EBC

 Verzeichnis von C:\Users\jensm\Desktop\local\GitHub\copyandpaste\Python_Libs\pytorch

11/24/2023  03:32 AM    <DIR>          .
10/30/2023  04:49 PM    <DIR>          ..
10/09/2023  04:51 PM    <DIR>          .ipynb_checkpoints
07/28/2023  05:30 PM            21,675 imagenet-classes.txt
11/24/2023  03:32 AM            37,138 pretrained_network.ipynb
10/25/2023  07:58 AM            54,787 pretrained_network2.ipynb
07/28/2023  05:18 PM           264,625 tiger.jpeg
08/01/2023  10:50 AM           185,788 Unbenannt.jpg
11/24/2023  03:29 AM             4,148 Untitled.ipynb
               6 Datei(en),        568,161 Bytes
               3 Verzeichnis(se), 232,576,995,328 Bytes frei


In [12]:
tiger = Image.open('tiger.jpeg')
tiger.show()

In [13]:
tiger_proc = preprocess(tiger)
tiger_proc

tensor([[[-0.7479, -0.7993, -0.8678,  ..., -1.3130, -1.5014, -1.6898],
         [-0.8507, -0.9192, -0.9363,  ..., -1.4672, -1.6555, -1.7583],
         [-0.9705, -1.0048, -1.0048,  ..., -1.6555, -1.7240, -1.6898],
         ...,
         [ 1.1529,  1.2043,  0.9132,  ..., -0.1999, -0.3369, -0.3198],
         [ 1.1529,  1.2899,  1.1872,  ..., -0.3712, -0.5253, -0.6281],
         [ 0.9646,  1.1529,  1.2728,  ..., -0.7993, -0.8335, -0.8678]],

        [[-0.1625, -0.2150, -0.2675,  ..., -0.9153, -1.1253, -1.3354],
         [-0.2500, -0.3200, -0.3550,  ..., -1.1078, -1.3004, -1.4055],
         [-0.3901, -0.4076, -0.4426,  ..., -1.2654, -1.3179, -1.3179],
         ...,
         [ 1.0630,  1.1856,  0.9055,  ..., -0.0049, -0.0574, -0.0749],
         [ 1.0280,  1.2381,  1.2206,  ..., -0.2150, -0.3200, -0.4426],
         [ 0.8529,  1.1155,  1.3606,  ..., -0.7402, -0.7577, -0.7927]],

        [[-1.0027, -1.0550, -1.0724,  ..., -1.0201, -1.3339, -1.5953],
         [-1.0898, -1.1247, -1.1596,  ..., -1

In [14]:
batch_t = torch.unsqueeze(tiger_proc, 0)
batch_t

tensor([[[[-0.7479, -0.7993, -0.8678,  ..., -1.3130, -1.5014, -1.6898],
          [-0.8507, -0.9192, -0.9363,  ..., -1.4672, -1.6555, -1.7583],
          [-0.9705, -1.0048, -1.0048,  ..., -1.6555, -1.7240, -1.6898],
          ...,
          [ 1.1529,  1.2043,  0.9132,  ..., -0.1999, -0.3369, -0.3198],
          [ 1.1529,  1.2899,  1.1872,  ..., -0.3712, -0.5253, -0.6281],
          [ 0.9646,  1.1529,  1.2728,  ..., -0.7993, -0.8335, -0.8678]],

         [[-0.1625, -0.2150, -0.2675,  ..., -0.9153, -1.1253, -1.3354],
          [-0.2500, -0.3200, -0.3550,  ..., -1.1078, -1.3004, -1.4055],
          [-0.3901, -0.4076, -0.4426,  ..., -1.2654, -1.3179, -1.3179],
          ...,
          [ 1.0630,  1.1856,  0.9055,  ..., -0.0049, -0.0574, -0.0749],
          [ 1.0280,  1.2381,  1.2206,  ..., -0.2150, -0.3200, -0.4426],
          [ 0.8529,  1.1155,  1.3606,  ..., -0.7402, -0.7577, -0.7927]],

         [[-1.0027, -1.0550, -1.0724,  ..., -1.0201, -1.3339, -1.5953],
          [-1.0898, -1.1247, -

In [15]:
#put the model in eval mode
resnet.eval();

In [16]:
#give him the picture(s)
out = resnet(batch_t)
out.shape

torch.Size([1, 1000])

In [17]:
#the output is a probability distribution over the imagenet-classes labels
with open('imagenet-classes.txt') as f:
    labels = [line.strip() for line in f.readlines()]

In [18]:
out.sort(descending=True);

In [19]:
_, index = torch.max(out, 1)

In [20]:
percentage = torch.nn.functional.softmax(out, dim=1)[0]
labels[index[0]], percentage[index[0]]

('tiger, Panthera tigris', tensor(0.8026, grad_fn=<SelectBackward0>))

In [21]:
#labels

In [22]:
_, indices = torch.sort(out, descending=True)
[(labels[idx], percentage[idx].item()) for idx in indices[0][:5]]

[('tiger, Panthera tigris', 0.8026196360588074),
 ('tiger cat', 0.18802422285079956),
 ('jaguar, panther, Panthera onca, Felis onca', 0.0017971842316910625),
 ('lynx, catamount', 0.00043622960220091045),
 ('patas, hussar monkey, Erythrocebus patas', 0.0003510267997626215)]