In [7]:
import torch
from torch import Tensor as T

In [8]:
type(torch.ones(3))

torch.Tensor

In [9]:
T([1,2,3,4]).reshape(2,2)

tensor([[1., 2.],
        [3., 4.]])

In [10]:
torch.tan(T([torch.pi/4]))

tensor([1.])

In [11]:
from torchvision import models
from torchvision import transforms

In [12]:
#dir(models)

In [13]:
#alexnet = models.AlexNet()
resnet = models.resnet101(pretrained=True)

C:\Users\jensm\anaconda3\Lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
C:\Users\jensm\anaconda3\Lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet101_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet101_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


In [14]:
resnet

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (downsample): Sequential(
        (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 

In [15]:
preprocess = transforms.Compose([
transforms.Resize(256),
transforms.CenterCrop(224),
transforms.ToTensor(),
transforms.Normalize(
mean=[0.485, 0.456, 0.406],
std=[0.229, 0.224, 0.225]
)])

In [16]:
import matplotlib.pyplot as plt
from PIL import Image

In [17]:
%ls

 Volume in Laufwerk C: hat keine Bezeichnung.
 Volumeseriennummer: A055-9EBC

 Verzeichnis von C:\Users\jensm\Desktop\local\GitHub\copyandpaste\Python_Libs\pytorch

10/25/2023  08:52 AM    <DIR>          .
10/22/2023  04:01 AM    <DIR>          ..
10/09/2023  05:51 PM    <DIR>          .ipynb_checkpoints
07/28/2023  06:30 PM            21,675 imagenet-classes.txt
08/21/2023  03:58 PM            37,215 pretrained_network.ipynb
10/25/2023  08:52 AM             6,251 pretrained_network2.ipynb
07/28/2023  06:18 PM           264,625 tiger.jpeg
08/01/2023  11:50 AM           185,788 Unbenannt.jpg
10/10/2023  11:06 PM             4,208 Untitled.ipynb
               6 Datei(en),        519,762 Bytes
               3 Verzeichnis(se), 126,567,321,600 Bytes frei


In [31]:
tiger = Image.open('unbenannt.jpg')
tiger.show()

In [19]:
tiger_proc = preprocess(tiger)
tiger_proc

tensor([[[ 1.4269,  1.3755,  1.3584,  ..., -0.8849, -0.9705, -0.9877],
         [ 1.3927,  1.3755,  1.3413,  ..., -0.9534, -1.0390, -1.0904],
         [ 1.3755,  1.3584,  1.3242,  ..., -1.1932, -1.2617, -1.3130],
         ...,
         [ 1.5297,  1.5297,  1.5297,  ..., -0.5424, -0.5767, -0.1486],
         [ 1.5468,  1.5297,  1.5297,  ..., -0.5253, -0.4397,  0.0569],
         [ 1.5639,  1.5639,  1.5639,  ..., -0.4397, -0.1828,  0.1597]],

        [[ 1.5707,  1.5182,  1.5007,  ..., -0.6527, -0.7052, -0.7227],
         [ 1.5357,  1.5182,  1.4832,  ..., -0.6877, -0.7577, -0.7927],
         [ 1.5182,  1.5007,  1.4832,  ..., -0.9153, -0.9678, -1.0203],
         ...,
         [ 1.7633,  1.7458,  1.7458,  ..., -0.7227, -0.7052, -0.1975],
         [ 1.7633,  1.7633,  1.7633,  ..., -0.7052, -0.5651,  0.0301],
         [ 1.7983,  1.7983,  1.7983,  ..., -0.6001, -0.2675,  0.1702]],

        [[ 1.7511,  1.6988,  1.6814,  ..., -0.5495, -0.6018, -0.6018],
         [ 1.7163,  1.6988,  1.6640,  ..., -0

In [20]:
batch_t = torch.unsqueeze(tiger_proc, 0)
batch_t

tensor([[[[ 1.4269,  1.3755,  1.3584,  ..., -0.8849, -0.9705, -0.9877],
          [ 1.3927,  1.3755,  1.3413,  ..., -0.9534, -1.0390, -1.0904],
          [ 1.3755,  1.3584,  1.3242,  ..., -1.1932, -1.2617, -1.3130],
          ...,
          [ 1.5297,  1.5297,  1.5297,  ..., -0.5424, -0.5767, -0.1486],
          [ 1.5468,  1.5297,  1.5297,  ..., -0.5253, -0.4397,  0.0569],
          [ 1.5639,  1.5639,  1.5639,  ..., -0.4397, -0.1828,  0.1597]],

         [[ 1.5707,  1.5182,  1.5007,  ..., -0.6527, -0.7052, -0.7227],
          [ 1.5357,  1.5182,  1.4832,  ..., -0.6877, -0.7577, -0.7927],
          [ 1.5182,  1.5007,  1.4832,  ..., -0.9153, -0.9678, -1.0203],
          ...,
          [ 1.7633,  1.7458,  1.7458,  ..., -0.7227, -0.7052, -0.1975],
          [ 1.7633,  1.7633,  1.7633,  ..., -0.7052, -0.5651,  0.0301],
          [ 1.7983,  1.7983,  1.7983,  ..., -0.6001, -0.2675,  0.1702]],

         [[ 1.7511,  1.6988,  1.6814,  ..., -0.5495, -0.6018, -0.6018],
          [ 1.7163,  1.6988,  

In [21]:
#put the model in eval mode
resnet.eval();

In [22]:
#give him the picture(s)
out = resnet(batch_t)
out.shape

torch.Size([1, 1000])

In [23]:
#the output is a probability distribution over the imagenet-classes labels
with open('imagenet-classes.txt') as f:
    labels = [line.strip() for line in f.readlines()]

In [24]:
out.sort(descending=True);

In [25]:
_, index = torch.max(out, 1)

In [26]:
out

tensor([[-1.7176e+00, -3.8202e-01, -2.8078e+00, -4.1648e+00, -2.3042e+00,
         -1.8328e+00, -2.5803e+00,  5.7553e-01, -1.7552e+00, -2.1832e+00,
         -2.4560e+00, -1.0163e+00, -3.5291e-01,  6.0226e-01, -9.5276e-02,
         -2.2524e+00, -2.7776e-01, -7.8700e-01, -1.0157e+00,  7.3685e-01,
         -2.6323e+00, -1.5862e+00, -7.3824e-01,  2.3604e-01, -1.2503e+00,
         -2.7063e+00, -1.9109e+00,  1.6666e-01, -6.3919e-01, -1.5886e+00,
         -2.3859e+00, -2.1289e+00, -4.1997e-01, -2.1135e+00, -2.2510e+00,
         -2.0778e+00, -2.1951e-02, -1.3815e+00, -3.1352e+00, -2.6103e+00,
         -1.6053e+00, -2.4895e+00, -2.4463e+00, -2.0250e+00, -1.4510e+00,
         -2.3153e+00, -1.5572e+00, -4.3931e-01, -3.5847e+00, -4.0810e+00,
         -3.8532e+00, -1.1860e+00,  1.0342e+00,  2.5150e-01,  1.3769e-01,
         -1.0290e+00, -1.1792e+00, -1.0899e+00, -3.8423e+00, -7.5083e-01,
         -1.1536e-01, -8.4224e-01, -3.6356e+00, -3.2159e+00, -2.5286e+00,
         -3.1576e+00, -2.3051e+00, -1.

In [27]:
percentage = torch.nn.functional.softmax(out, dim=1)[0]
labels[index[0]], percentage[index[0]]

('wig', tensor(0.9736, grad_fn=<SelectBackward0>))

In [28]:
#labels

In [29]:
_, indices = torch.sort(out, descending=True)
[(labels[idx], percentage[idx].item()) for idx in indices[0][:5]]

[('wig', 0.973638117313385),
 ('hair spray', 0.006498284637928009),
 ('hand blower, blow dryer, blow drier, hair dryer, hair drier',
  0.0044490862637758255),
 ('hair slide', 0.0029669145587831736),
 ('mortarboard', 0.002086340682581067)]