In [38]:
import torch
from torch import Tensor as T

In [39]:
type(torch.ones(3))

torch.Tensor

In [40]:
T([1,2,3,4]).reshape(2,2)

tensor([[1., 2.],
        [3., 4.]])

In [41]:
torch.tan(T([torch.pi/4]))

tensor([1.])

In [42]:
from torchvision import models
from torchvision import transforms

In [3]:
#dir(models)

In [6]:
#alexnet = models.AlexNet()
#resnet = models.resnet101(pretrained=True)

C:\Users\jensm\AppData\Local\Programs\Python\Python311\Lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
C:\Users\jensm\AppData\Local\Programs\Python\Python311\Lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet101_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet101_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Downloading: "https://download.pytorch.org/models/resnet101-63fe2227.pth" to C:\Users\jensm/.cache\torch\hub\checkpoints\resnet101-63fe2227.pth
100.0%


In [43]:
resnet

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (downsample): Sequential(
        (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 

In [44]:
preprocess = transforms.Compose([
transforms.Resize(256),
transforms.CenterCrop(224),
transforms.ToTensor(),
transforms.Normalize(
mean=[0.485, 0.456, 0.406],
std=[0.229, 0.224, 0.225]
)])

In [45]:
import matplotlib.pyplot as plt
from PIL import Image

In [46]:
%ls

 Volume in Laufwerk C: hat keine Bezeichnung.
 Volumeseriennummer: A055-9EBC

 Verzeichnis von C:\Users\jensm\Desktop\local\GitHub\copyandpaste\Python_Libs\pytorch

07/28/2023  06:25 PM    <DIR>          .
07/27/2023  03:28 PM    <DIR>          ..
07/20/2023  04:15 AM    <DIR>          .ipynb_checkpoints
07/28/2023  06:25 PM            32,722 pretrained_network.ipynb
07/28/2023  06:18 PM           264,625 tiger.jpeg
07/28/2023  06:13 PM           144,658 Velkoz_0.jpg
               3 Datei(en),        442,005 Bytes
               3 Verzeichnis(se), 213,284,167,680 Bytes frei


In [48]:
tiger = Image.open('tiger.jpeg')
#tiger.convert('L').show()

In [49]:
tiger_proc = preprocess(tiger)
tiger_proc

tensor([[[-0.7479, -0.7993, -0.8507,  ..., -1.2959, -1.5014, -1.6898],
         [-0.8507, -0.9192, -0.9363,  ..., -1.4672, -1.6555, -1.7583],
         [-0.9534, -1.0048, -0.9877,  ..., -1.6555, -1.7069, -1.6898],
         ...,
         [ 1.1529,  1.2043,  0.9132,  ..., -0.1999, -0.3198, -0.3198],
         [ 1.1529,  1.2899,  1.1872,  ..., -0.3712, -0.5253, -0.6281],
         [ 0.9817,  1.1529,  1.2728,  ..., -0.7993, -0.8335, -0.8678]],

        [[-0.1625, -0.2150, -0.2675,  ..., -0.9153, -1.1253, -1.3354],
         [-0.2500, -0.3200, -0.3550,  ..., -1.1078, -1.3004, -1.4055],
         [-0.3901, -0.4251, -0.4426,  ..., -1.2654, -1.3179, -1.3179],
         ...,
         [ 1.0630,  1.1681,  0.9055,  ..., -0.0049, -0.0574, -0.0749],
         [ 1.0280,  1.2381,  1.2206,  ..., -0.2150, -0.3200, -0.4426],
         [ 0.8529,  1.1155,  1.3606,  ..., -0.7402, -0.7577, -0.7927]],

        [[-1.0027, -1.0550, -1.0724,  ..., -1.0201, -1.3339, -1.5953],
         [-1.0898, -1.1247, -1.1596,  ..., -1

In [56]:
batch_t = torch.unsqueeze(tiger_proc, 0)
batch_t

tensor([[[[-0.7479, -0.7993, -0.8507,  ..., -1.2959, -1.5014, -1.6898],
          [-0.8507, -0.9192, -0.9363,  ..., -1.4672, -1.6555, -1.7583],
          [-0.9534, -1.0048, -0.9877,  ..., -1.6555, -1.7069, -1.6898],
          ...,
          [ 1.1529,  1.2043,  0.9132,  ..., -0.1999, -0.3198, -0.3198],
          [ 1.1529,  1.2899,  1.1872,  ..., -0.3712, -0.5253, -0.6281],
          [ 0.9817,  1.1529,  1.2728,  ..., -0.7993, -0.8335, -0.8678]],

         [[-0.1625, -0.2150, -0.2675,  ..., -0.9153, -1.1253, -1.3354],
          [-0.2500, -0.3200, -0.3550,  ..., -1.1078, -1.3004, -1.4055],
          [-0.3901, -0.4251, -0.4426,  ..., -1.2654, -1.3179, -1.3179],
          ...,
          [ 1.0630,  1.1681,  0.9055,  ..., -0.0049, -0.0574, -0.0749],
          [ 1.0280,  1.2381,  1.2206,  ..., -0.2150, -0.3200, -0.4426],
          [ 0.8529,  1.1155,  1.3606,  ..., -0.7402, -0.7577, -0.7927]],

         [[-1.0027, -1.0550, -1.0724,  ..., -1.0201, -1.3339, -1.5953],
          [-1.0898, -1.1247, -

In [67]:
#put the model in eval mode
resnet.eval();

In [65]:
#give him the picture(s)
out = resnet(batch_t)
out.shape

torch.Size([1, 1000])

In [61]:
#the output is a probability distribution over the imagenet-classes labels
with open('imagenet-classes.txt') as f:
    labels = [line.strip() for line in f.readlines()]

In [62]:
_, index = torch.max(out, 1)

In [63]:
index

tensor([292])

In [64]:
percentage = torch.nn.functional.softmax(out, dim=1)[0] * 100
labels[index[0]], percentage[index[0]].item()

('tiger, Panthera tigris', 80.8843765258789)

In [68]:
labels

['tench, Tinca tinca',
 'goldfish, Carassius auratus',
 'great white shark, white shark, man-eater, man-eating shark, Carcharodon carcharias',
 'tiger shark, Galeocerdo cuvieri',
 'hammerhead, hammerhead shark',
 'electric ray, crampfish, numbfish, torpedo',
 'stingray',
 'cock',
 'hen',
 'ostrich, Struthio camelus',
 'brambling, Fringilla montifringilla',
 'goldfinch, Carduelis carduelis',
 'house finch, linnet, Carpodacus mexicanus',
 'junco, snowbird',
 'indigo bunting, indigo finch, indigo bird, Passerina cyanea',
 'robin, American robin, Turdus migratorius',
 'bulbul',
 'jay',
 'magpie',
 'chickadee',
 'water ouzel, dipper',
 'kite',
 'bald eagle, American eagle, Haliaeetus leucocephalus',
 'vulture',
 'great grey owl, great gray owl, Strix nebulosa',
 'European fire salamander, Salamandra salamandra',
 'common newt, Triturus vulgaris',
 'eft',
 'spotted salamander, Ambystoma maculatum',
 'axolotl, mud puppy, Ambystoma mexicanum',
 'bullfrog, Rana catesbeiana',
 'tree frog, tree-f