In [10]:
import torch
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('dark_background')

In [11]:
torch.__version__

'2.1.0+cpu'

In [12]:
np.array([10])

array([10])

In [13]:
x = torch.tensor([2.0], requires_grad=True)
y = torch.sin(x)
y.backward()  # Computes gradients
print(x.grad) 

tensor([-0.4161])


In [14]:
x.stride()

(1,)

In [15]:
A = torch.ones(10,10)
B = A.t()
print(A.stride(), B.stride())

(10, 1) (1, 10)


In [16]:
B[1] = 10
A

tensor([[ 1., 10.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1., 10.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1., 10.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1., 10.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1., 10.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1., 10.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1., 10.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1., 10.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1., 10.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1., 10.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [17]:
dump = lambda **kwargs: kwargs

In [18]:
dump(**{'x':3,'c': 4})

{'x': 3, 'c': 4}