In [51]:
import torch

In [52]:
A = torch.arange(72).reshape(12,6).float()
A

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.],
        [12., 13., 14., 15., 16., 17.],
        [18., 19., 20., 21., 22., 23.],
        [24., 25., 26., 27., 28., 29.],
        [30., 31., 32., 33., 34., 35.],
        [36., 37., 38., 39., 40., 41.],
        [42., 43., 44., 45., 46., 47.],
        [48., 49., 50., 51., 52., 53.],
        [54., 55., 56., 57., 58., 59.],
        [60., 61., 62., 63., 64., 65.],
        [66., 67., 68., 69., 70., 71.]])

In [53]:
transform = torch.eye(6,14)
transform

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [54]:
(A@transform)

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 6.,  7.,  8.,  9., 10., 11.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [12., 13., 14., 15., 16., 17.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [18., 19., 20., 21., 22., 23.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [24., 25., 26., 27., 28., 29.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [30., 31., 32., 33., 34., 35.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [36., 37., 38., 39., 40., 41.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [42., 43., 44., 45., 46., 47.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [48., 49., 50., 51., 52., 53.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [54., 55., 56., 57., 58., 59.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [60., 61., 62., 63., 64., 65.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [66., 67., 68., 69., 70., 71.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])