In [11]:
import torch
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('dark_background')

In [12]:
torch.__version__

'2.2.0+cpu'

In [13]:
np.array([10])

array([10])

In [14]:
x = torch.tensor([2.0], requires_grad=True)
y = torch.sin(x)
y.backward()  # Computes gradients
print(x.grad) 

tensor([-0.4161])


In [15]:
x.stride()

(1,)

In [16]:
A = torch.ones(10,10)
B = A.t()
print(A.stride(), B.stride())

(10, 1) (1, 10)


In [17]:
B[1] = 10
A

tensor([[ 1., 10.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1., 10.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1., 10.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1., 10.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1., 10.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1., 10.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1., 10.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1., 10.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1., 10.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1., 10.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [18]:
dump = lambda **kwargs: kwargs

In [19]:
dump(**{'x':3,'c': 4})

{'x': 3, 'c': 4}

In [28]:
f = lambda x: 3*x**2 - 4*x

In [31]:
for h in 10**np.arange(-1,-6, -1, dtype=float):
    print(f'h={h:.5f}, numerical limit= {(f(1+h) - f(1)) / h:.5f}')

h=0.10000, numerical limit= 2.30000
h=0.01000, numerical limit= 2.03000
h=0.00100, numerical limit= 2.00300
h=0.00010, numerical limit= 2.00030
h=0.00001, numerical limit= 2.00003
