In [173]:
import numpy as np

In [174]:
rg = np.random.default_rng(4)
rg.random((2,3))

array([[0.94305611, 0.51132755, 0.97624371],
       [0.08083602, 0.60735583, 0.37648658]])

In [175]:
L = np.arange(12).reshape(3,4)
L

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [176]:
print(L.sum())
print(L.cumsum())

66
[ 0  1  3  6 10 15 21 28 36 45 55 66]


In [177]:
L.sum(axis=1), L.sum(axis=0)

(array([ 6, 22, 38]), array([12, 15, 18, 21]))

In [178]:
L.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

In [179]:
L.cumsum(axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]], dtype=int32)

In [180]:
L

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [181]:
A = np.arange(24).reshape((2,2,3,2))
A[0,0].size

6

In [182]:
A[1,0,1] = 0
A

array([[[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]]],


       [[[12, 13],
         [ 0,  0],
         [16, 17]],

        [[18, 19],
         [20, 21],
         [22, 23]]]])

In [183]:
A[...,1]

array([[[ 1,  3,  5],
        [ 7,  9, 11]],

       [[13,  0, 17],
        [19, 21, 23]]])

In [184]:
D = np.arange(288).reshape(2,3,2,6,4)
D[0,...,1,1]

array([[  5,  29],
       [ 53,  77],
       [101, 125]])

In [185]:
D[0]

array([[[[  0,   1,   2,   3],
         [  4,   5,   6,   7],
         [  8,   9,  10,  11],
         [ 12,  13,  14,  15],
         [ 16,  17,  18,  19],
         [ 20,  21,  22,  23]],

        [[ 24,  25,  26,  27],
         [ 28,  29,  30,  31],
         [ 32,  33,  34,  35],
         [ 36,  37,  38,  39],
         [ 40,  41,  42,  43],
         [ 44,  45,  46,  47]]],


       [[[ 48,  49,  50,  51],
         [ 52,  53,  54,  55],
         [ 56,  57,  58,  59],
         [ 60,  61,  62,  63],
         [ 64,  65,  66,  67],
         [ 68,  69,  70,  71]],

        [[ 72,  73,  74,  75],
         [ 76,  77,  78,  79],
         [ 80,  81,  82,  83],
         [ 84,  85,  86,  87],
         [ 88,  89,  90,  91],
         [ 92,  93,  94,  95]]],


       [[[ 96,  97,  98,  99],
         [100, 101, 102, 103],
         [104, 105, 106, 107],
         [108, 109, 110, 111],
         [112, 113, 114, 115],
         [116, 117, 118, 119]],

        [[120, 121, 122, 123],
         [124, 125, 126, 

In [186]:
A = np.arange(36).reshape((3,3,4))
A

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [187]:
A[0,0,:]

array([0, 1, 2, 3])

In [188]:
A = np.array([1,2,3,4,5,6,7,8,9,10], dtype = np.float64)
A

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [189]:
r = A.copy()
for i in range(1,3):
    r += np.concatenate((r[:i] / i, A[:-i]))
r/3

array([1. , 1.5, 2. , 3. , 4. , 5. , 6. , 7. , 8. , 9. ])

In [190]:
r

array([ 3. ,  4.5,  6. ,  9. , 12. , 15. , 18. , 21. , 24. , 27. ])

In [191]:
L4 = np.arange(100).reshape((2, 10, 5))
L4

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [192]:
c = 0
for i in L4:
    c+=1
c

2

In [193]:
arr = np.array([[1, 2], [3, 4]])

for index, value in np.ndenumerate(arr):
    print(index, value)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [194]:
indices = [(index, value) for index, value in np.ndenumerate(np.arange(30).reshape(2, 5, 3))]
indices

[((0, 0, 0), 0),
 ((0, 0, 1), 1),
 ((0, 0, 2), 2),
 ((0, 1, 0), 3),
 ((0, 1, 1), 4),
 ((0, 1, 2), 5),
 ((0, 2, 0), 6),
 ((0, 2, 1), 7),
 ((0, 2, 2), 8),
 ((0, 3, 0), 9),
 ((0, 3, 1), 10),
 ((0, 3, 2), 11),
 ((0, 4, 0), 12),
 ((0, 4, 1), 13),
 ((0, 4, 2), 14),
 ((1, 0, 0), 15),
 ((1, 0, 1), 16),
 ((1, 0, 2), 17),
 ((1, 1, 0), 18),
 ((1, 1, 1), 19),
 ((1, 1, 2), 20),
 ((1, 2, 0), 21),
 ((1, 2, 1), 22),
 ((1, 2, 2), 23),
 ((1, 3, 0), 24),
 ((1, 3, 1), 25),
 ((1, 3, 2), 26),
 ((1, 4, 0), 27),
 ((1, 4, 1), 28),
 ((1, 4, 2), 29)]

In [195]:
A2 = np.zeros(30).reshape((2, 5, 3))

for index, value in indices:
    A2[index] = value   
A2

array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.],
        [12., 13., 14.]],

       [[15., 16., 17.],
        [18., 19., 20.],
        [21., 22., 23.],
        [24., 25., 26.],
        [27., 28., 29.]]])

In [196]:
np.arange(30).reshape(2, 5, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [197]:
import sys
sys.version

'3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)]'

In [198]:
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9]

even_numbers = [x if x % 2 == 0 else 'odd' for x in numbers]

In [199]:
even_numbers

['odd', 2, 'odd', 4, 'odd', 6, 'odd', 8, 'odd']

In [200]:
sum_indices = lambda a, b: 10 * (a + b) 

arr = np.fromfunction(sum_indices, (4, 4))
arr

array([[ 0., 10., 20., 30.],
       [10., 20., 30., 40.],
       [20., 30., 40., 50.],
       [30., 40., 50., 60.]])

In [201]:
A_ = np.floor(10 * rg.random((3, 4)))

In [202]:
A_.flat[7] = 20
A_

array([[ 8.,  1.,  8.,  5.],
       [ 9.,  4.,  4., 20.],
       [ 9.,  3.,  9.,  9.]])

In [203]:
A_.ravel()

array([ 8.,  1.,  8.,  5.,  9.,  4.,  4., 20.,  9.,  3.,  9.,  9.])

In [204]:
A_.ravel(order='F')

array([ 8.,  9.,  9.,  1.,  4.,  3.,  8.,  4.,  9.,  5., 20.,  9.])

In [205]:
A_.T

array([[ 8.,  9.,  9.],
       [ 1.,  4.,  3.],
       [ 8.,  4.,  9.],
       [ 5., 20.,  9.]])

In [206]:
A_.reshape((6,2))

array([[ 8.,  1.],
       [ 8.,  5.],
       [ 9.,  4.],
       [ 4., 20.],
       [ 9.,  3.],
       [ 9.,  9.]])

In [207]:
A_.resize((2,6)) #resize will modify the input array
A_

array([[ 8.,  1.,  8.,  5.,  9.,  4.],
       [ 4., 20.,  9.,  3.,  9.,  9.]])

In [208]:
A2 = np.arange(60).reshape(2,10,3)

In [209]:
A2_sliced = A2[1,:,2].ravel()
A2_sliced

array([32, 35, 38, 41, 44, 47, 50, 53, 56, 59])

In [210]:
A3 = rg.integers(low=0, high=20, size=(2,3,4))
A3

array([[[11,  3,  9, 12],
        [ 6, 14,  8, 18],
        [ 4, 13,  1,  2]],

       [[10,  9,  9,  9],
        [17, 10,  7, 19],
        [17,  6,  4,  4]]], dtype=int64)

In [211]:
np.argmin(A3, axis=0)

array([[1, 0, 0, 1],
       [0, 1, 1, 0],
       [0, 1, 0, 0]], dtype=int64)

In [212]:
np.argmin(A3, axis=1)

array([[2, 0, 2, 2],
       [0, 2, 2, 2]], dtype=int64)

In [213]:
np.argmin(A3, axis=2)

array([[1, 0, 2],
       [1, 2, 2]], dtype=int64)

In [223]:
np.random.randint(20, size=(3,3))

array([[ 9,  4,  9],
       [ 7, 18, 10],
       [14,  3,  3]])