### Most of the times I am just going through numpy manual in this notebook

In [1]:
import numpy as np

In [2]:
rg = np.random.default_rng(4)
rg.random((2,3))

array([[0.94305611, 0.51132755, 0.97624371],
       [0.08083602, 0.60735583, 0.37648658]])

In [3]:
L = np.arange(12).reshape(3,4)
L

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
print(L.sum())
print(L.cumsum())

66
[ 0  1  3  6 10 15 21 28 36 45 55 66]


In [5]:
L.sum(axis=1), L.sum(axis=0)

(array([ 6, 22, 38]), array([12, 15, 18, 21]))

In [6]:
L.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

In [7]:
L.cumsum(axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]], dtype=int32)

In [8]:
L

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
A = np.arange(24).reshape((2,2,3,2))
A[0,0].size

6

In [10]:
A[1,0,1] = 0
A

array([[[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]]],


       [[[12, 13],
         [ 0,  0],
         [16, 17]],

        [[18, 19],
         [20, 21],
         [22, 23]]]])

In [11]:
A[...,1]

array([[[ 1,  3,  5],
        [ 7,  9, 11]],

       [[13,  0, 17],
        [19, 21, 23]]])

In [12]:
D = np.arange(288).reshape(2,3,2,6,4)
D[0,...,1,1]

array([[  5,  29],
       [ 53,  77],
       [101, 125]])

In [13]:
D[0]

array([[[[  0,   1,   2,   3],
         [  4,   5,   6,   7],
         [  8,   9,  10,  11],
         [ 12,  13,  14,  15],
         [ 16,  17,  18,  19],
         [ 20,  21,  22,  23]],

        [[ 24,  25,  26,  27],
         [ 28,  29,  30,  31],
         [ 32,  33,  34,  35],
         [ 36,  37,  38,  39],
         [ 40,  41,  42,  43],
         [ 44,  45,  46,  47]]],


       [[[ 48,  49,  50,  51],
         [ 52,  53,  54,  55],
         [ 56,  57,  58,  59],
         [ 60,  61,  62,  63],
         [ 64,  65,  66,  67],
         [ 68,  69,  70,  71]],

        [[ 72,  73,  74,  75],
         [ 76,  77,  78,  79],
         [ 80,  81,  82,  83],
         [ 84,  85,  86,  87],
         [ 88,  89,  90,  91],
         [ 92,  93,  94,  95]]],


       [[[ 96,  97,  98,  99],
         [100, 101, 102, 103],
         [104, 105, 106, 107],
         [108, 109, 110, 111],
         [112, 113, 114, 115],
         [116, 117, 118, 119]],

        [[120, 121, 122, 123],
         [124, 125, 126, 

In [14]:
A = np.arange(36).reshape((3,3,4))
A

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [15]:
A[0,0,:]

array([0, 1, 2, 3])

In [16]:
A = np.array([1,2,3,4,5,6,7,8,9,10], dtype = np.float64)
A

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [17]:
r = A.copy()
for i in range(1,3):
    r += np.concatenate((r[:i] / i, A[:-i]))
r/3

array([1. , 1.5, 2. , 3. , 4. , 5. , 6. , 7. , 8. , 9. ])

In [18]:
r

array([ 3. ,  4.5,  6. ,  9. , 12. , 15. , 18. , 21. , 24. , 27. ])

In [19]:
L4 = np.arange(100).reshape((2, 10, 5))
L4

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [20]:
c = 0
for i in L4:
    c+=1
c

2

In [21]:
arr = np.array([[1, 2], [3, 4]])

for index, value in np.ndenumerate(arr):
    print(index, value)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [22]:
indices = [(index, value) for index, value in np.ndenumerate(np.arange(30).reshape(2, 5, 3))]
indices

[((0, 0, 0), 0),
 ((0, 0, 1), 1),
 ((0, 0, 2), 2),
 ((0, 1, 0), 3),
 ((0, 1, 1), 4),
 ((0, 1, 2), 5),
 ((0, 2, 0), 6),
 ((0, 2, 1), 7),
 ((0, 2, 2), 8),
 ((0, 3, 0), 9),
 ((0, 3, 1), 10),
 ((0, 3, 2), 11),
 ((0, 4, 0), 12),
 ((0, 4, 1), 13),
 ((0, 4, 2), 14),
 ((1, 0, 0), 15),
 ((1, 0, 1), 16),
 ((1, 0, 2), 17),
 ((1, 1, 0), 18),
 ((1, 1, 1), 19),
 ((1, 1, 2), 20),
 ((1, 2, 0), 21),
 ((1, 2, 1), 22),
 ((1, 2, 2), 23),
 ((1, 3, 0), 24),
 ((1, 3, 1), 25),
 ((1, 3, 2), 26),
 ((1, 4, 0), 27),
 ((1, 4, 1), 28),
 ((1, 4, 2), 29)]

In [23]:
A2 = np.zeros(30).reshape((2, 5, 3))

for index, value in indices:
    A2[index] = value   
A2

array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.],
        [12., 13., 14.]],

       [[15., 16., 17.],
        [18., 19., 20.],
        [21., 22., 23.],
        [24., 25., 26.],
        [27., 28., 29.]]])

In [24]:
np.arange(30).reshape(2, 5, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [25]:
import sys
sys.version

'3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)]'

In [26]:
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9]
even_numbers = [x if x % 2 == 0 else 'odd' for x in numbers]
even_numbers

['odd', 2, 'odd', 4, 'odd', 6, 'odd', 8, 'odd']

In [27]:
sum_indices = lambda a, b: 10 * (a + b) 

arr = np.fromfunction(sum_indices, (4, 4))
arr

array([[ 0., 10., 20., 30.],
       [10., 20., 30., 40.],
       [20., 30., 40., 50.],
       [30., 40., 50., 60.]])

In [28]:
A_ = np.floor(10 * rg.random((3, 4)))
A_.flat[7] = 20
A_

array([[ 8.,  1.,  8.,  5.],
       [ 9.,  4.,  4., 20.],
       [ 9.,  3.,  9.,  9.]])

In [29]:
A_.ravel()

array([ 8.,  1.,  8.,  5.,  9.,  4.,  4., 20.,  9.,  3.,  9.,  9.])

In [30]:
A_.ravel(order='F')

array([ 8.,  9.,  9.,  1.,  4.,  3.,  8.,  4.,  9.,  5., 20.,  9.])

In [31]:
A_.T

array([[ 8.,  9.,  9.],
       [ 1.,  4.,  3.],
       [ 8.,  4.,  9.],
       [ 5., 20.,  9.]])

In [32]:
A_.reshape((6,2))

array([[ 8.,  1.],
       [ 8.,  5.],
       [ 9.,  4.],
       [ 4., 20.],
       [ 9.,  3.],
       [ 9.,  9.]])

In [33]:
A_.resize((2,6)) #resize will modify the input array
A_

array([[ 8.,  1.,  8.,  5.,  9.,  4.],
       [ 4., 20.,  9.,  3.,  9.,  9.]])

In [34]:
A2 = np.arange(60).reshape(2,10,3)

In [35]:
A2_sliced = A2[1,:,2].ravel()
A2_sliced

array([32, 35, 38, 41, 44, 47, 50, 53, 56, 59])

In [36]:
A3 = rg.integers(low=0, high=20, size=(2,3,4))
A3

array([[[11,  3,  9, 12],
        [ 6, 14,  8, 18],
        [ 4, 13,  1,  2]],

       [[10,  9,  9,  9],
        [17, 10,  7, 19],
        [17,  6,  4,  4]]], dtype=int64)

In [37]:
np.argmin(A3, axis=0)

array([[1, 0, 0, 1],
       [0, 1, 1, 0],
       [0, 1, 0, 0]], dtype=int64)

In [38]:
np.argmin(A3, axis=1)

array([[2, 0, 2, 2],
       [0, 2, 2, 2]], dtype=int64)

In [39]:
np.argmin(A3, axis=2)

array([[1, 0, 2],
       [1, 2, 2]], dtype=int64)

In [40]:
np.random.randint(20, size=(3,3))

array([[ 1,  5,  5],
       [17, 12,  8],
       [17,  7, 13]])

-----

-----

## stacking arrays

In [41]:
A5 = np.floor(10 * rg.random((5,10)))
A6 = np.floor(10 * rg.random((5,10)))
np.hstack((A5,A6)).shape, np.vstack((A5,A6)).shape

((5, 20), (10, 10))

In [42]:
a = np.floor(10 * rg.random((4, 5)))
b = np.floor(10 * rg.random((4, 1)))
b

array([[3.],
       [9.],
       [7.],
       [3.]])

In [43]:
np.column_stack((a, b))

array([[8., 9., 8., 3., 6., 3.],
       [7., 0., 7., 0., 9., 9.],
       [2., 9., 2., 5., 8., 7.],
       [9., 7., 8., 3., 7., 3.]])

In [44]:
a_ = np.floor(10 * rg.random((2, 5)))
b_ = np.floor(10 * rg.random((1, 5)))
b_

array([[3., 3., 2., 4., 7.]])

In [45]:
np.r_[a_,b_] == np.row_stack((a_, b_))

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [46]:
np.row_stack is np.vstack, np.column_stack is np.hstack

(True, False)

In [47]:
np.floor(10*rg.random((2,3,2)))

array([[[8., 6.],
        [7., 9.],
        [6., 0.]],

       [[6., 0.],
        [6., 9.],
        [4., 9.]]])

In [48]:
a2 = np.zeros((2,3,4))
b2 = np.ones((2,3,4))
a2

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [49]:
np.concatenate((a2, b2), axis=0)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [50]:
np.concatenate((a2, b2), axis=1)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [51]:
np.concatenate((a2, b2), axis=2)

array([[[0., 0., 0., 0., 1., 1., 1., 1.],
        [0., 0., 0., 0., 1., 1., 1., 1.],
        [0., 0., 0., 0., 1., 1., 1., 1.]],

       [[0., 0., 0., 0., 1., 1., 1., 1.],
        [0., 0., 0., 0., 1., 1., 1., 1.],
        [0., 0., 0., 0., 1., 1., 1., 1.]]])

In [52]:
row1 = np.r_[1:70:4j, 0, 20, 3:5]
col1 = np.c_[2:200:4j,2:6]
col2 = np.c_[2:9]
row1, col1

(array([ 1., 24., 47., 70.,  0., 20.,  3.,  4.]),
 array([[  2.,   2.],
        [ 68.,   3.],
        [134.,   4.],
        [200.,   5.]]))

In [53]:
np.c_[row1,row1].T

array([[ 1., 24., 47., 70.,  0., 20.,  3.,  4.],
       [ 1., 24., 47., 70.,  0., 20.,  3.,  4.]])

In [54]:
#broadcast
array1 = row1 + col2
array1

array([[ 3., 26., 49., 72.,  2., 22.,  5.,  6.],
       [ 4., 27., 50., 73.,  3., 23.,  6.,  7.],
       [ 5., 28., 51., 74.,  4., 24.,  7.,  8.],
       [ 6., 29., 52., 75.,  5., 25.,  8.,  9.],
       [ 7., 30., 53., 76.,  6., 26.,  9., 10.],
       [ 8., 31., 54., 77.,  7., 27., 10., 11.],
       [ 9., 32., 55., 78.,  8., 28., 11., 12.]])

In [55]:
print(np.c_[array1,array1])
#np.r_[array1,array1]

[[ 3. 26. 49. 72.  2. 22.  5.  6.  3. 26. 49. 72.  2. 22.  5.  6.]
 [ 4. 27. 50. 73.  3. 23.  6.  7.  4. 27. 50. 73.  3. 23.  6.  7.]
 [ 5. 28. 51. 74.  4. 24.  7.  8.  5. 28. 51. 74.  4. 24.  7.  8.]
 [ 6. 29. 52. 75.  5. 25.  8.  9.  6. 29. 52. 75.  5. 25.  8.  9.]
 [ 7. 30. 53. 76.  6. 26.  9. 10.  7. 30. 53. 76.  6. 26.  9. 10.]
 [ 8. 31. 54. 77.  7. 27. 10. 11.  8. 31. 54. 77.  7. 27. 10. 11.]
 [ 9. 32. 55. 78.  8. 28. 11. 12.  9. 32. 55. 78.  8. 28. 11. 12.]]


In [56]:
np.c_[5:100:20j] + np.r_[10:100:10j]

array([[ 15.,  25.,  35.,  45.,  55.,  65.,  75.,  85.,  95., 105.],
       [ 20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100., 110.],
       [ 25.,  35.,  45.,  55.,  65.,  75.,  85.,  95., 105., 115.],
       [ 30.,  40.,  50.,  60.,  70.,  80.,  90., 100., 110., 120.],
       [ 35.,  45.,  55.,  65.,  75.,  85.,  95., 105., 115., 125.],
       [ 40.,  50.,  60.,  70.,  80.,  90., 100., 110., 120., 130.],
       [ 45.,  55.,  65.,  75.,  85.,  95., 105., 115., 125., 135.],
       [ 50.,  60.,  70.,  80.,  90., 100., 110., 120., 130., 140.],
       [ 55.,  65.,  75.,  85.,  95., 105., 115., 125., 135., 145.],
       [ 60.,  70.,  80.,  90., 100., 110., 120., 130., 140., 150.],
       [ 65.,  75.,  85.,  95., 105., 115., 125., 135., 145., 155.],
       [ 70.,  80.,  90., 100., 110., 120., 130., 140., 150., 160.],
       [ 75.,  85.,  95., 105., 115., 125., 135., 145., 155., 165.],
       [ 80.,  90., 100., 110., 120., 130., 140., 150., 160., 170.],
       [ 85.,  95., 105., 115., 12

In [57]:
#np.newaxis will create only a view 
k = np.r_[10:100:10j]
l = np.c_[10:100:10j]
k2 = k.copy()[:, np.newaxis] 
k2

array([[ 10.],
       [ 20.],
       [ 30.],
       [ 40.],
       [ 50.],
       [ 60.],
       [ 70.],
       [ 80.],
       [ 90.],
       [100.]])

------

## splitting arrays

In [58]:
myA = np.r_[10:80:8j] + np.c_[20:80:4j] 
myA

array([[ 30.,  40.,  50.,  60.,  70.,  80.,  90., 100.],
       [ 50.,  60.,  70.,  80.,  90., 100., 110., 120.],
       [ 70.,  80.,  90., 100., 110., 120., 130., 140.],
       [ 90., 100., 110., 120., 130., 140., 150., 160.]])

In [59]:
#np.hsplit, np.vsplit and np.array_split will also only create a view
x, *y = np.hsplit(myA, 4) 
x 

array([[ 30.,  40.],
       [ 50.,  60.],
       [ 70.,  80.],
       [ 90., 100.]])

In [60]:
np.hsplit(myA, (2,5,6)) #see how it works?

[array([[ 30.,  40.],
        [ 50.,  60.],
        [ 70.,  80.],
        [ 90., 100.]]),
 array([[ 50.,  60.,  70.],
        [ 70.,  80.,  90.],
        [ 90., 100., 110.],
        [110., 120., 130.]]),
 array([[ 80.],
        [100.],
        [120.],
        [140.]]),
 array([[ 90., 100.],
        [110., 120.],
        [130., 140.],
        [150., 160.]])]

In [61]:
o,p = np.vsplit(myA, 2)
o

array([[ 30.,  40.,  50.,  60.,  70.,  80.,  90., 100.],
       [ 50.,  60.,  70.,  80.,  90., 100., 110., 120.]])

In [62]:
np.array_split(myA, 4,axis=0)

[array([[ 30.,  40.,  50.,  60.,  70.,  80.,  90., 100.]]),
 array([[ 50.,  60.,  70.,  80.,  90., 100., 110., 120.]]),
 array([[ 70.,  80.,  90., 100., 110., 120., 130., 140.]]),
 array([[ 90., 100., 110., 120., 130., 140., 150., 160.]])]

In [63]:
a, *b = np.array_split(myA.copy(), 4,axis=0) 
a[0,1] = 200 
a

array([[ 30., 200.,  50.,  60.,  70.,  80.,  90., 100.]])

In [64]:
u = p
id(u) == id(p)

True

In [65]:
v_p = p.view()
v_p.resize((4,4))
p #p.shape is not changing

array([[ 70.,  80.,  90., 100., 110., 120., 130., 140.],
       [ 90., 100., 110., 120., 130., 140., 150., 160.]])

In [66]:
v_p[:,3] = 0 #however values of p do change
p

array([[ 70.,  80.,  90.,   0., 110., 120., 130.,   0.],
       [ 90., 100., 110.,   0., 130., 140., 150.,   0.]])

In [67]:
myA

array([[ 30.,  40.,  50.,  60.,  70.,  80.,  90., 100.],
       [ 50.,  60.,  70.,  80.,  90., 100., 110., 120.],
       [ 70.,  80.,  90.,   0., 110., 120., 130.,   0.],
       [ 90., 100., 110.,   0., 130., 140., 150.,   0.]])

--------

## Indexing

In [68]:
a = np.arange(6)**2
index = [1,2,3,4]
index_f = np.array([1, 1, 0, 4, 6, 2])
index2d = np.array([[1,2], [2,3], [3,4]])
index_bool = np.array([True,False,True,False,True,False])

In [69]:
b = a[index_bool]
c = a[index2d]
d = a[2]
e = a[index]
a[2] = 0
c

array([[ 1,  4],
       [ 4,  9],
       [ 9, 16]], dtype=int32)

In [70]:
b.base is a, c.base is a, e.base is a

(False, False, False)

In [71]:
_array = np.arange(50).reshape((5, 10))
_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [72]:
i = [[2, 1], [2, 3]]
j = [[0, 1], [1, 2]]
i2 = [1,2,3]
j2 = [1,2,3]

In [73]:
_array[i, j] #i and j as the first and second dimension of _array

array([[20, 11],
       [21, 32]])

In [74]:
_array[[1,2,3], [2,0,0]]

array([12, 20, 30])

In [75]:
_array[[1,2,3], 2]

array([12, 22, 32])

In [76]:
_array[2, [1,2,3]]

array([21, 22, 23])

In [77]:
_array[:, 3:5]

array([[ 3,  4],
       [13, 14],
       [23, 24],
       [33, 34],
       [43, 44]])

In [78]:
l = (i, j) # arr[(i, j)] equivalent to arr[i, j] 
_array[l]

array([[20, 11],
       [21, 32]])

In [79]:
#another example of broadcasting
np.zeros((8, 2)) + np.array([2, 2])

array([[2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.]])

In [91]:
time = np.linspace(20, 100, 5)
data = np.sin(np.arange(20)).reshape(5,4)

In [92]:
time

array([ 20.,  40.,  60.,  80., 100.])

In [93]:
data

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721]])

In [94]:
ind = data.argmax(axis=0)
ind

array([2, 0, 3, 1], dtype=int64)

In [111]:
time_max = time[ind]
data_max = data[ind, range(data.shape[1])]    
data_max

array([0.98935825, 0.84147098, 0.99060736, 0.6569866 ])

In [113]:
for i in range(data.shape[1]):
    print(data[ind[i], i])

0.9893582466233818
0.8414709848078965
0.9906073556948704
0.6569865987187891


In [115]:
np.all(data.max(axis=0) == data_max)

True

In [116]:
a = np.arange(5)
a[[1,3,4]] = 0
a

array([0, 0, 2, 0, 0])

--------

In [96]:
(lambda x: (x % 2 and 'odd' or 'even'))(4) #lol

'even'

In [97]:
SUM = (lambda a: a.sum(axis=1))(np.ones((4,5))) #IIFE
SUM

array([5., 5., 5., 5.])

In [98]:
(lambda *a: sum(a))(1,2,3)

6

In [99]:
(lambda **k: sum(k.values()))(one=1, two=2, three=3)

6