In [169]:
import numpy as np

In [170]:
rg = np.random.default_rng(4)
rg.random((2,3))

array([[0.94305611, 0.51132755, 0.97624371],
       [0.08083602, 0.60735583, 0.37648658]])

In [171]:
L = np.arange(12).reshape(3,4)
L

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [172]:
print(L.sum())
print(L.cumsum())

66
[ 0  1  3  6 10 15 21 28 36 45 55 66]


In [173]:
L.sum(axis=1), L.sum(axis=0)

(array([ 6, 22, 38]), array([12, 15, 18, 21]))

In [174]:
L.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

In [175]:
L.cumsum(axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]], dtype=int32)

In [176]:
L

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [177]:
A = np.arange(24).reshape((2,2,3,2))
A[0,0].size

6

In [178]:
A[1,0,1] = 0
A

array([[[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]]],


       [[[12, 13],
         [ 0,  0],
         [16, 17]],

        [[18, 19],
         [20, 21],
         [22, 23]]]])

In [179]:
A[...,1]

array([[[ 1,  3,  5],
        [ 7,  9, 11]],

       [[13,  0, 17],
        [19, 21, 23]]])

In [180]:
D = np.arange(288).reshape(2,3,2,6,4)
D[0,...,1,1]

array([[  5,  29],
       [ 53,  77],
       [101, 125]])

In [181]:
D[0]

array([[[[  0,   1,   2,   3],
         [  4,   5,   6,   7],
         [  8,   9,  10,  11],
         [ 12,  13,  14,  15],
         [ 16,  17,  18,  19],
         [ 20,  21,  22,  23]],

        [[ 24,  25,  26,  27],
         [ 28,  29,  30,  31],
         [ 32,  33,  34,  35],
         [ 36,  37,  38,  39],
         [ 40,  41,  42,  43],
         [ 44,  45,  46,  47]]],


       [[[ 48,  49,  50,  51],
         [ 52,  53,  54,  55],
         [ 56,  57,  58,  59],
         [ 60,  61,  62,  63],
         [ 64,  65,  66,  67],
         [ 68,  69,  70,  71]],

        [[ 72,  73,  74,  75],
         [ 76,  77,  78,  79],
         [ 80,  81,  82,  83],
         [ 84,  85,  86,  87],
         [ 88,  89,  90,  91],
         [ 92,  93,  94,  95]]],


       [[[ 96,  97,  98,  99],
         [100, 101, 102, 103],
         [104, 105, 106, 107],
         [108, 109, 110, 111],
         [112, 113, 114, 115],
         [116, 117, 118, 119]],

        [[120, 121, 122, 123],
         [124, 125, 126, 

In [182]:
A = np.arange(36).reshape((3,3,4))
A

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [183]:
A[0,0,:]

array([0, 1, 2, 3])

In [184]:
A = np.array([1,2,3,4,5,6,7,8,9,10], dtype = np.float64)
A

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [185]:
r = A.copy()
for i in range(1,3):
    r += np.concatenate((r[:i] / i, A[:-i]))
r/3

array([1. , 1.5, 2. , 3. , 4. , 5. , 6. , 7. , 8. , 9. ])

In [186]:
r

array([ 3. ,  4.5,  6. ,  9. , 12. , 15. , 18. , 21. , 24. , 27. ])

In [187]:
L4 = np.arange(100).reshape((2, 10, 5))
L4

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [188]:
c = 0
for i in L4:
    c+=1
c

2

In [189]:
arr = np.array([[1, 2], [3, 4]])

for index, value in np.ndenumerate(arr):
    print(index, value)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [190]:
indices = [(index, value) for index, value in np.ndenumerate(np.arange(30).reshape(2, 5, 3))]
indices

[((0, 0, 0), 0),
 ((0, 0, 1), 1),
 ((0, 0, 2), 2),
 ((0, 1, 0), 3),
 ((0, 1, 1), 4),
 ((0, 1, 2), 5),
 ((0, 2, 0), 6),
 ((0, 2, 1), 7),
 ((0, 2, 2), 8),
 ((0, 3, 0), 9),
 ((0, 3, 1), 10),
 ((0, 3, 2), 11),
 ((0, 4, 0), 12),
 ((0, 4, 1), 13),
 ((0, 4, 2), 14),
 ((1, 0, 0), 15),
 ((1, 0, 1), 16),
 ((1, 0, 2), 17),
 ((1, 1, 0), 18),
 ((1, 1, 1), 19),
 ((1, 1, 2), 20),
 ((1, 2, 0), 21),
 ((1, 2, 1), 22),
 ((1, 2, 2), 23),
 ((1, 3, 0), 24),
 ((1, 3, 1), 25),
 ((1, 3, 2), 26),
 ((1, 4, 0), 27),
 ((1, 4, 1), 28),
 ((1, 4, 2), 29)]

In [191]:
A2 = np.zeros(30).reshape((2, 5, 3))

for index, value in indices:
    A2[index] = value   
A2

array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.],
        [12., 13., 14.]],

       [[15., 16., 17.],
        [18., 19., 20.],
        [21., 22., 23.],
        [24., 25., 26.],
        [27., 28., 29.]]])

In [192]:
np.arange(30).reshape(2, 5, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [193]:
import sys
sys.version

'3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)]'

In [194]:
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9]
even_numbers = [x if x % 2 == 0 else 'odd' for x in numbers]
even_numbers

['odd', 2, 'odd', 4, 'odd', 6, 'odd', 8, 'odd']

In [195]:
sum_indices = lambda a, b: 10 * (a + b) 

arr = np.fromfunction(sum_indices, (4, 4))
arr

array([[ 0., 10., 20., 30.],
       [10., 20., 30., 40.],
       [20., 30., 40., 50.],
       [30., 40., 50., 60.]])

In [196]:
A_ = np.floor(10 * rg.random((3, 4)))
A_.flat[7] = 20
A_

array([[ 8.,  1.,  8.,  5.],
       [ 9.,  4.,  4., 20.],
       [ 9.,  3.,  9.,  9.]])

In [197]:
A_.ravel()

array([ 8.,  1.,  8.,  5.,  9.,  4.,  4., 20.,  9.,  3.,  9.,  9.])

In [198]:
A_.ravel(order='F')

array([ 8.,  9.,  9.,  1.,  4.,  3.,  8.,  4.,  9.,  5., 20.,  9.])

In [199]:
A_.T

array([[ 8.,  9.,  9.],
       [ 1.,  4.,  3.],
       [ 8.,  4.,  9.],
       [ 5., 20.,  9.]])

In [200]:
A_.reshape((6,2))

array([[ 8.,  1.],
       [ 8.,  5.],
       [ 9.,  4.],
       [ 4., 20.],
       [ 9.,  3.],
       [ 9.,  9.]])

In [201]:
A_.resize((2,6)) #resize will modify the input array
A_

array([[ 8.,  1.,  8.,  5.,  9.,  4.],
       [ 4., 20.,  9.,  3.,  9.,  9.]])

In [202]:
A2 = np.arange(60).reshape(2,10,3)

In [203]:
A2_sliced = A2[1,:,2].ravel()
A2_sliced

array([32, 35, 38, 41, 44, 47, 50, 53, 56, 59])

In [204]:
A3 = rg.integers(low=0, high=20, size=(2,3,4))
A3

array([[[11,  3,  9, 12],
        [ 6, 14,  8, 18],
        [ 4, 13,  1,  2]],

       [[10,  9,  9,  9],
        [17, 10,  7, 19],
        [17,  6,  4,  4]]], dtype=int64)

In [205]:
np.argmin(A3, axis=0)

array([[1, 0, 0, 1],
       [0, 1, 1, 0],
       [0, 1, 0, 0]], dtype=int64)

In [206]:
np.argmin(A3, axis=1)

array([[2, 0, 2, 2],
       [0, 2, 2, 2]], dtype=int64)

In [207]:
np.argmin(A3, axis=2)

array([[1, 0, 2],
       [1, 2, 2]], dtype=int64)

In [208]:
np.random.randint(20, size=(3,3))

array([[19, 17,  0],
       [19, 17, 17],
       [ 9,  9, 15]])

In [209]:
#stacking 2 arrays horizontal and vertical
A5 = np.floor(10 * rg.random((5,10)))
A6 = np.floor(10 * rg.random((5,10)))
np.hstack((A5,A6)).shape, np.vstack((A5,A6)).shape

((5, 20), (10, 10))

In [210]:
a = np.floor(10 * rg.random((4, 5)))
b = np.floor(10 * rg.random((4, 1)))
b

array([[3.],
       [9.],
       [7.],
       [3.]])

In [211]:
np.column_stack((a, b))

array([[8., 9., 8., 3., 6., 3.],
       [7., 0., 7., 0., 9., 9.],
       [2., 9., 2., 5., 8., 7.],
       [9., 7., 8., 3., 7., 3.]])

In [212]:
a_ = np.floor(10 * rg.random((2, 5)))
b_ = np.floor(10 * rg.random((1, 5)))
b_

array([[3., 3., 2., 4., 7.]])

In [213]:
np.row_stack((a_, b_))

array([[7., 0., 9., 6., 3.],
       [6., 7., 6., 8., 4.],
       [3., 3., 2., 4., 7.]])

In [214]:
np.row_stack is np.vstack, np.column_stack is np.hstack

(True, False)

In [215]:
np.floor(10*rg.random((2,3,2)))

array([[[8., 6.],
        [7., 9.],
        [6., 0.]],

       [[6., 0.],
        [6., 9.],
        [4., 9.]]])

In [216]:
a2 = np.zeros((2,3,4))
b2 = np.ones((2,3,4))
a2

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [217]:
np.concatenate((a2, b2), axis=0)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [218]:
np.concatenate((a2, b2), axis=1)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [219]:
np.concatenate((a2, b2), axis=2)

array([[[0., 0., 0., 0., 1., 1., 1., 1.],
        [0., 0., 0., 0., 1., 1., 1., 1.],
        [0., 0., 0., 0., 1., 1., 1., 1.]],

       [[0., 0., 0., 0., 1., 1., 1., 1.],
        [0., 0., 0., 0., 1., 1., 1., 1.],
        [0., 0., 0., 0., 1., 1., 1., 1.]]])

In [220]:
row1 = np.r_[1:70:4j, 0, 20, 3:5]
col1 = np.c_[2:200:4j,2:6]
col2 = np.c_[2:9]
row1, col1

(array([ 1., 24., 47., 70.,  0., 20.,  3.,  4.]),
 array([[  2.,   2.],
        [ 68.,   3.],
        [134.,   4.],
        [200.,   5.]]))

In [221]:
np.c_[row1,row1].T

array([[ 1., 24., 47., 70.,  0., 20.,  3.,  4.],
       [ 1., 24., 47., 70.,  0., 20.,  3.,  4.]])

In [222]:
#broadcast
array1 = row1 + col2
array1

array([[ 3., 26., 49., 72.,  2., 22.,  5.,  6.],
       [ 4., 27., 50., 73.,  3., 23.,  6.,  7.],
       [ 5., 28., 51., 74.,  4., 24.,  7.,  8.],
       [ 6., 29., 52., 75.,  5., 25.,  8.,  9.],
       [ 7., 30., 53., 76.,  6., 26.,  9., 10.],
       [ 8., 31., 54., 77.,  7., 27., 10., 11.],
       [ 9., 32., 55., 78.,  8., 28., 11., 12.]])

In [223]:
print(np.c_[array1,array1])
#np.r_[array1,array1]

[[ 3. 26. 49. 72.  2. 22.  5.  6.  3. 26. 49. 72.  2. 22.  5.  6.]
 [ 4. 27. 50. 73.  3. 23.  6.  7.  4. 27. 50. 73.  3. 23.  6.  7.]
 [ 5. 28. 51. 74.  4. 24.  7.  8.  5. 28. 51. 74.  4. 24.  7.  8.]
 [ 6. 29. 52. 75.  5. 25.  8.  9.  6. 29. 52. 75.  5. 25.  8.  9.]
 [ 7. 30. 53. 76.  6. 26.  9. 10.  7. 30. 53. 76.  6. 26.  9. 10.]
 [ 8. 31. 54. 77.  7. 27. 10. 11.  8. 31. 54. 77.  7. 27. 10. 11.]
 [ 9. 32. 55. 78.  8. 28. 11. 12.  9. 32. 55. 78.  8. 28. 11. 12.]]


In [224]:
np.c_[5:100:20j] + np.r_[10:100:10j]

array([[ 15.,  25.,  35.,  45.,  55.,  65.,  75.,  85.,  95., 105.],
       [ 20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100., 110.],
       [ 25.,  35.,  45.,  55.,  65.,  75.,  85.,  95., 105., 115.],
       [ 30.,  40.,  50.,  60.,  70.,  80.,  90., 100., 110., 120.],
       [ 35.,  45.,  55.,  65.,  75.,  85.,  95., 105., 115., 125.],
       [ 40.,  50.,  60.,  70.,  80.,  90., 100., 110., 120., 130.],
       [ 45.,  55.,  65.,  75.,  85.,  95., 105., 115., 125., 135.],
       [ 50.,  60.,  70.,  80.,  90., 100., 110., 120., 130., 140.],
       [ 55.,  65.,  75.,  85.,  95., 105., 115., 125., 135., 145.],
       [ 60.,  70.,  80.,  90., 100., 110., 120., 130., 140., 150.],
       [ 65.,  75.,  85.,  95., 105., 115., 125., 135., 145., 155.],
       [ 70.,  80.,  90., 100., 110., 120., 130., 140., 150., 160.],
       [ 75.,  85.,  95., 105., 115., 125., 135., 145., 155., 165.],
       [ 80.,  90., 100., 110., 120., 130., 140., 150., 160., 170.],
       [ 85.,  95., 105., 115., 12

In [225]:
#np.newaxis will create only a view 
k = np.r_[10:100:10j]
l = np.c_[10:100:10j]
k2 = k.copy()[:, np.newaxis] 
k2

array([[ 10.],
       [ 20.],
       [ 30.],
       [ 40.],
       [ 50.],
       [ 60.],
       [ 70.],
       [ 80.],
       [ 90.],
       [100.]])

In [226]:
myA = np.r_[10:80:8j] + np.c_[20:80:4j] 
myA

array([[ 30.,  40.,  50.,  60.,  70.,  80.,  90., 100.],
       [ 50.,  60.,  70.,  80.,  90., 100., 110., 120.],
       [ 70.,  80.,  90., 100., 110., 120., 130., 140.],
       [ 90., 100., 110., 120., 130., 140., 150., 160.]])

In [227]:
x, *y = np.hsplit(myA, 4)
x

array([[ 30.,  40.],
       [ 50.,  60.],
       [ 70.,  80.],
       [ 90., 100.]])

In [228]:
np.hsplit(myA, (2,5,6)) #see how it works?

[array([[ 30.,  40.],
        [ 50.,  60.],
        [ 70.,  80.],
        [ 90., 100.]]),
 array([[ 50.,  60.,  70.],
        [ 70.,  80.,  90.],
        [ 90., 100., 110.],
        [110., 120., 130.]]),
 array([[ 80.],
        [100.],
        [120.],
        [140.]]),
 array([[ 90., 100.],
        [110., 120.],
        [130., 140.],
        [150., 160.]])]

In [229]:
o,p = np.vsplit(myA, 2)
o

array([[ 30.,  40.,  50.,  60.,  70.,  80.,  90., 100.],
       [ 50.,  60.,  70.,  80.,  90., 100., 110., 120.]])

In [230]:
u = p
id(u) == id(p)

True

In [231]:
v_p = p.view()
v_p.reshape((4,4))
p #p.shape is not changing

array([[ 70.,  80.,  90., 100., 110., 120., 130., 140.],
       [ 90., 100., 110., 120., 130., 140., 150., 160.]])

In [232]:
v_p[:,3] = 0 #however values of p do change
p

array([[ 70.,  80.,  90.,   0., 110., 120., 130., 140.],
       [ 90., 100., 110.,   0., 130., 140., 150., 160.]])

In [233]:
myA

array([[ 30.,  40.,  50.,  60.,  70.,  80.,  90., 100.],
       [ 50.,  60.,  70.,  80.,  90., 100., 110., 120.],
       [ 70.,  80.,  90.,   0., 110., 120., 130., 140.],
       [ 90., 100., 110.,   0., 130., 140., 150., 160.]])