In [54]:
import math
import statistics
import numpy as np
import scipy.stats
import pandas as pd
import matplotlib.pyplot as plt

In [55]:
#calculate weighted arithmetic mean

data = [8.0, 1, 2.5, 4, 28.0] 
weights = [0.1, 0.2, 0.3, 0.25, 0.15]

np_data = np.array(data)
np_weights = np.array(weights)

list_ = []

for i in range(len(data)):
    list_.append(data[i]* weights[i])

    
wmean1 = sum(list_) /len(data) 
wmean2 = sum([weights[j]*data[j] for j in range(len(data))]) /len(data)
wmean3 = np.average([data[j]*weights[j] for j in range(len(data))])

In [56]:
#True

wmean1 == wmean2 == wmean3

True

In [57]:
def calculate_stats(values):
    minimum = min(values)
    maximum = max(values)
    average = sum(values) / len(values)
    return minimum, maximum, average

minimum, maximum, average = calculate_stats([1, 2, 3, 4, 5])

In [58]:
arr = np.random.randint(low=1, high=20, size=20)

condition = lambda x: (x > 5) & (x < 15)
filtered_arr1 = list(filter(condition,arr)) 

indices = np.where(5 < arr)
filtered_arr2 = arr[indices]
 

filtered_arr1, filtered_arr2

([13, 14, 9, 9, 14, 14, 11, 7, 8, 7],
 array([13, 14, 18,  9,  9, 17, 14, 14, 19, 11,  7, 18, 17,  8,  7]))

In [19]:
#lambda rules

def perms1(L):
    if len(L) <=1:
        return (L,)
    else:
        return tuple((L[i],) + P for i in range(len(L)) for P in perms1(L[:i] + L[i+1:]))
    
    
perms2 = lambda L: tuple((L[i],) + P for i in range(len(L)) for P in perms2(L[:i] + L[i+1:])) if len(L) > 1 else (L,)
fac = lambda n: 1 if n == 0 else n * fac(n-1)

In [20]:
len(perms1((1,2,3,4,5))) == len(perms2((1,2,3,4,5))) == fac(5) #true

True

In [21]:
perms1([1,2,3)

TypeError: can only concatenate tuple (not "list") to tuple

In [62]:
#broadcast in numpy

x = np.array([[1,2,3]])
y = np.array([[1],
              [2],
              [3]])

x+y

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [63]:
#matrix multiplication

np.matrix([[1,2,3],[4,5,6]]) * np.matrix([[1,2],
                                          [3,4],
                                          [5,6]]) 

matrix([[22, 28],
        [49, 64]])

- $Q = {q_1, q_2, ..., q_n}$ is the set of states
- $\Sigma = {a_1, a_2, ..., a_m}$ is the set of input symbols
- $q_0$ is the initial state
- $F = {f_1, f_2, ..., f_n}$ is the set of final or accepting states
- $\delta : Q \times \Sigma \rightarrow Q$ is the transition function, where $\delta(q_i, a_j) = q_k$ is the next state when the machine is in state $q_i$ and receives input symbol $a_j$