In [81]:
import math
import statistics
import numpy as np
import scipy.stats
import pandas as pd
import matplotlib.pyplot as plt

In [82]:
#calculate weighted arithmetic mean

data = [8.0, 1, 2.5, 4, 28.0] 
weights = [0.1, 0.2, 0.3, 0.25, 0.15]

np_data = np.array(data)
np_weights = np.array(weights)

list_ = []

for i in range(len(data)):
    list_.append(data[i]* weights[i])

    
wmean1 = sum(list_) /len(data) 
wmean2 = sum([weights[j]*data[j] for j in range(len(data))]) /len(data)
wmean3 = np.average([data[j]*weights[j] for j in range(len(data))])

In [83]:
#True

wmean1 == wmean2 == wmean3

True

In [84]:
def calculate_stats(values):
    minimum = min(values)
    maximum = max(values)
    average = sum(values) / len(values)
    return minimum, maximum, average

minimum, maximum, average = calculate_stats([1, 2, 3, 4, 5])

In [85]:
arr = np.random.randint(low=1, high=20, size=20)

condition = lambda x: (x > 5) & (x < 15)
filtered_arr1 = list(filter(condition,arr)) 

indices = np.where(5 < arr)
filtered_arr2 = arr[indices]
 

filtered_arr1, filtered_arr2

([8, 7, 14, 12, 10, 9, 9, 13, 14, 13, 12, 11, 14],
 array([ 8,  7, 14, 12, 10,  9,  9, 15, 15, 18, 13, 15, 14, 18, 13, 12, 11,
        14]))

------------------------------

# Combinatorics

In [104]:
#lambda rules

perms2 = lambda L: tuple((L[i],) + P for i in range(len(L)) for P in perms2(L[:i] + L[i+1:])) if len(L) > 1 else (L,)
pwr = lambda T: len(set(perms2(T)))
fac = lambda n: 1 if n == 0 else n * fac(n-1)

In [105]:
#permutation without repitition

perms2((1,2,3))

((1, 2, 3), (1, 3, 2), (2, 1, 3), (2, 3, 1), (3, 1, 2), (3, 2, 1))

In [106]:
#permutation with repitition 

set(perms2((1,2,2,2)))

{(1, 2, 2, 2), (2, 1, 2, 2), (2, 2, 1, 2), (2, 2, 2, 1)}

In [107]:
len(perms2((1,2,3,4,5))) == fac(5)

True

In [108]:
len(set(perms2((1,2,2,2)))) == pwr((1,2,2,2)) == fac(4)/(fac(1)*fac(3)) 

True

In [109]:
pwr((1,2,2,3,3)) == fac(5)/(fac(1)*fac(2)*fac(2))

True

In [110]:
pwr((1,1,2,2,2,3,3,3,3)) == fac(9)/(fac(2)*fac(3)*fac(4))

True

In [92]:
#broadcast in numpy

x = np.array([[1,2,3]])
y = np.array([[1],
              [2],
              [3]])

x+y

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [93]:
#matrix multiplication

np.matrix([[1,2,3],[4,5,6]]) * np.matrix([[1,2],
                                          [3,4],
                                          [5,6]]) 

matrix([[22, 28],
        [49, 64]])

- $Q = {q_1, q_2, ..., q_n}$ is the set of states
- $\Sigma = {a_1, a_2, ..., a_m}$ is the set of input symbols
- $q_0$ is the initial state
- $F = {f_1, f_2, ..., f_n}$ is the set of final or accepting states
- $\delta : Q \times \Sigma \rightarrow Q$ is the transition function, where $\delta(q_i, a_j) = q_k$ is the next state when the machine is in state $q_i$ and receives input symbol $a_j$