In [1]:
import math
import statistics
import numpy as np
import scipy.stats
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#calculate weighted arithmetic mean

data = [8.0, 1, 2.5, 4, 28.0] 
weights = [0.1, 0.2, 0.3, 0.25, 0.15]

np_data = np.array(data)
np_weights = np.array(weights)

list_ = []

for i in range(len(data)):
    list_.append(data[i]* weights[i])

    
wmean1 = sum(list_) /len(data) 
wmean2 = sum([weights[j]*data[j] for j in range(len(data))]) /len(data)
wmean3 = np.average([data[j]*weights[j] for j in range(len(data))])

In [3]:
#True

wmean1 == wmean2 == wmean3

True

In [4]:
def calculate_stats(values):
    minimum = min(values)
    maximum = max(values)
    average = sum(values) / len(values)
    return minimum, maximum, average

minimum, maximum, average = calculate_stats([1, 2, 3, 4, 5])

In [5]:
arr = np.random.randint(low=1, high=20, size=20)

condition = lambda x: (x > 5) & (x < 15)
filtered_arr1 = list(filter(condition,arr)) 

indices = np.where(5 < arr)
filtered_arr2 = arr[indices]
 

filtered_arr1, filtered_arr2

([7, 11, 8, 6, 6, 6, 7, 6, 12],
 array([ 7, 11, 15,  8,  6,  6,  6, 17,  7, 15, 18,  6, 12, 15]))

In [6]:
#lambda rules

def perms1(L):
    if len(L) <=1:
        return (L,)
    else:
        return tuple((L[i],) + P for i in range(len(L)) for P in perms1(L[:i] + L[i+1:]))
    
    
perms2 = lambda L: tuple((L[i],) + P for i in range(len(L)) for P in perms2(L[:i] + L[i+1:])) if len(L) > 1 else (L,)
fac = lambda n: 1 if n == 0 else n * fac(n-1)

len(perms1((1,2,3,4,5))) == len(perms2((1,2,3,4,5))) == fac(5)

True

In [14]:
#permutation without repitition

perms2((1,2,3,4))

((1, 2, 3, 4),
 (1, 2, 4, 3),
 (1, 3, 2, 4),
 (1, 3, 4, 2),
 (1, 4, 2, 3),
 (1, 4, 3, 2),
 (2, 1, 3, 4),
 (2, 1, 4, 3),
 (2, 3, 1, 4),
 (2, 3, 4, 1),
 (2, 4, 1, 3),
 (2, 4, 3, 1),
 (3, 1, 2, 4),
 (3, 1, 4, 2),
 (3, 2, 1, 4),
 (3, 2, 4, 1),
 (3, 4, 1, 2),
 (3, 4, 2, 1),
 (4, 1, 2, 3),
 (4, 1, 3, 2),
 (4, 2, 1, 3),
 (4, 2, 3, 1),
 (4, 3, 1, 2),
 (4, 3, 2, 1))

In [27]:
#permutation with repitition 

set(perms2((1,2,2,2)))

{(1, 2, 2, 2), (2, 1, 2, 2), (2, 2, 1, 2), (2, 2, 2, 1)}

In [28]:
pwr = lambda T: len(set(perms2(T)))

In [29]:
len(set(perms2((1,2,2,2)))) == pwr((1,2,2,2)) == fac(4)/fac(3) 

True

In [35]:
pwr((1,2,2,3,3)) == fac(5)/(fac(2)*fac(2))

True

In [9]:
#broadcast in numpy

x = np.array([[1,2,3]])
y = np.array([[1],
              [2],
              [3]])

x+y

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [10]:
#matrix multiplication

np.matrix([[1,2,3],[4,5,6]]) * np.matrix([[1,2],
                                          [3,4],
                                          [5,6]]) 

matrix([[22, 28],
        [49, 64]])

- $Q = {q_1, q_2, ..., q_n}$ is the set of states
- $\Sigma = {a_1, a_2, ..., a_m}$ is the set of input symbols
- $q_0$ is the initial state
- $F = {f_1, f_2, ..., f_n}$ is the set of final or accepting states
- $\delta : Q \times \Sigma \rightarrow Q$ is the transition function, where $\delta(q_i, a_j) = q_k$ is the next state when the machine is in state $q_i$ and receives input symbol $a_j$