In [1]:
import math
import statistics
import numpy as np
import scipy.stats
import pandas as pd
import matplotlib.pyplot as plt

In [16]:
x_nan = [1,2,3,math.nan,4,5]

np_a = np.array(x_nan)
pd_s = pd.Series(x_nan)

statistics.fmean(x_nan), np.mean(x_nan), np.average(x_nan), np.mean(np_a), np_a.mean()

(nan, nan, nan, nan, nan)

In [20]:
np.nanmean(np_a), pd_s.mean(), pd_s.mean(skipna=False)

(3.0, 3.0, nan)

In [56]:
#calculate weighted arithmetic mean

data = [8.0, 1, 2.5, 4, 28.0] 
weights = [0.1, 0.2, 0.3, 0.25, 0.15]

a,b,w = np.array(data),pd.Series(data), np.array(weights)

    
wmean1 = sum(weights[_]*data[_] for _ in range(len(data))) /sum(weights)
wmean2 = sum(i*j for (i,j) in zip(data, weights)) / sum(weights)
wmean3 = (a*w).sum()/w.sum() 
wmean4 = np.average(data,weights=weights)

In [57]:
wmean1 == wmean2 == wmean3 == wmean4

True

In [4]:
def calculate_stats(values):
    minimum = min(values)
    maximum = max(values)
    average = sum(values) / len(values)
    return minimum, maximum, average

minimum, maximum, average = calculate_stats([1, 2, 3, 4, 5])

In [25]:
wmean2

1.3900000000000001

In [5]:
arr = np.random.randint(low=1, high=20, size=20)

condition = lambda x: (x > 5) & (x < 15)
filtered_arr1 = list(filter(condition,arr)) 

indices = np.where(5 < arr)
filtered_arr2 = arr[indices]
 

filtered_arr1, filtered_arr2

([10, 12, 8, 10, 12, 14, 14, 14, 11],
 array([10, 19, 16, 12,  8, 10, 12, 17, 14, 14, 19, 15, 14, 19, 11]))

In [6]:
#broadcast in numpy

x = np.array([[1,2,3]])
y = np.array([[1],
              [2],
              [3]])

x+y

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [7]:
#matrix multiplication

np.matrix([[1,2,3],[4,5,6]]) * np.matrix([[1,2],
                                          [3,4],
                                          [5,6]]) 

matrix([[22, 28],
        [49, 64]])

- $Q = {q_1, q_2, ..., q_n}$ is the set of states
- $\Sigma = {a_1, a_2, ..., a_m}$ is the set of input symbols
- $q_0$ is the initial state
- $F = {f_1, f_2, ..., f_n}$ is the set of final or accepting states
- $\delta : Q \times \Sigma \rightarrow Q$ is the transition function, where $\delta(q_i, a_j) = q_k$ is the next state when the machine is in state $q_i$ and receives input symbol $a_j$