In [28]:
import math
import statistics
import numpy as np
import scipy.stats
import pandas as pd

In [29]:
x = [8.0, 1, 2.5, 4, 28.0]
w = [0.1, 0.2, 0.3, 0.25, 0.15]

list_ = []

for i in range(len(x)):
    list_.append(w[i]* x[i])

wmean = sum(list_)   
    
y = np.array(x)
w2 = np.array(w)

In [30]:
(w2 * y).sum()

6.95

In [31]:
v = (w* y)

In [32]:
v

array([0.8 , 0.2 , 0.75, 1.  , 4.2 ])

In [33]:
list_

[0.8, 0.2, 0.75, 1.0, 4.2]

In [34]:
wmean2 = np.average(y, weights = w2)

In [35]:
wmean2

6.95

In [36]:
aa = (w[i] * x[i] for i in range(len(x)))

In [37]:
x = 100
 
for i in range(3):
    
    x = x >> 1
    
print(x)

12


In [38]:
30 >> 3

3

In [39]:
30/ 3**2

3.3333333333333335

In [40]:
import numpy as np

# Create an array of random integers
arr = np.random.randint(low=0, high=10, size=6)
print(arr)

# Find the indices of all elements greater than 5
indices = np.where(arr > 5)
print(indices)

# Use the indices to filter the array
filtered_arr = arr[[2, 3, 5]]
print(filtered_arr)


[0 0 9 4 6 0]
(array([2, 4], dtype=int64),)
[9 4 0]


In [41]:
arr = np.random.randint(low=0, high=10, size=6)

In [42]:
arr

array([7, 8, 6, 3, 8, 5])

In [43]:
arr = arr[[1,3,4,5]]

In [44]:
arr

array([8, 3, 8, 5])

In [45]:
x = np.array([[1,2,3]])
y = np.array([[1],
              [2],
              [3]])

In [46]:
y

array([[1],
       [2],
       [3]])

In [47]:
x

array([[1, 2, 3]])

In [48]:
x+y

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [49]:
def calculate_stats(values):
    minimum = min(values)
    maximum = max(values)
    average = sum(values) / len(values)
    return minimum, maximum, average

minimum, maximum, average = calculate_stats([1, 2, 3, 4, 5])


type(calculate_stats([1, 2, 3, 4, 5]))

tuple

In [50]:
import math
3 /  1.73205

1.732051615138131

In [51]:
math.sqrt(3)

1.7320508075688772

In [52]:
np.matrix([[1,2,3],[4,5,6]]) * np.matrix([[1,2],
                                          [3,4],
                                          [5,6]]) 

matrix([[22, 28],
        [49, 64]])

In [53]:
import numpy as np
import matplotlib.pyplot as plt

# Sample data
x = [1, 2, 3, 4, 5, 3, 6]
y = [2, 4, 5, 4, 5, 7, 3]

# Mean of x and y
mean_x = np.mean(x)
mean_y = np.mean(y)

# Total number of observations
n = len(x)

# Using the formula to calculate the b1 and b0
numer = 0
denom = 0
for i in range(n):
    numer += (x[i] - mean_x) * (y[i] - mean_y)
    denom += (x[i] - mean_x) ** 2
b1 = numer / denom
b0 = mean_y - (b1 * mean_x)

# Print coefficients
print("b1 =", b1)
print("b0 =", b0)

b1 = 0.12096774193548386
b0 = 3.870967741935484


- $Q = {q_1, q_2, ..., q_n}$ is the set of states
- $\Sigma = {a_1, a_2, ..., a_m}$ is the set of input symbols
- $q_0$ is the initial state
- $F = {f_1, f_2, ..., f_n}$ is the set of final or accepting states
- $\delta : Q \times \Sigma \rightarrow Q$ is the transition function, where $\delta(q_i, a_j) = q_k$ is the next state when the machine is in state $q_i$ and receives input symbol $a_j$