In [73]:
import math
import statistics
import numpy as np
import scipy.stats
import pandas as pd

In [74]:
#calculate weighted arithmetic mean

data = [8.0, 1, 2.5, 4, 28.0] 
weights = [0.1, 0.2, 0.3, 0.25, 0.15]

np_data = np.array(data)
np_weights = np.array(weights)

list_ = []

for i in range(len(data)):
    list_.append(data[i]* weights[i])

    
wmean1 = sum(list_) /len(data) 
wmean2 = sum([weights[j]*data[j] for j in range(len(data))]) /len(data)
wmean3 = np.average([data[j]*weights[j] for j in range(len(data))])

In [75]:
#True

wmean1 == wmean2 == wmean3

True

In [95]:
arr = np.random.randint(low=0, high=20, size=30)

indices = np.where(arr > 5)
filtered_arr = arr[indices]

filtered_arr

array([17, 10,  9, 10,  8, 17, 14, 11, 11, 10, 17, 18, 11, 16, 16, 18, 19])

In [81]:
def calculate_stats(values):
    minimum = min(values)
    maximum = max(values)
    average = sum(values) / len(values)
    return minimum, maximum, average

minimum, maximum, average = calculate_stats([1, 2, 3, 4, 5])


type(calculate_stats([1, 2, 3, 4, 5]))

tuple

In [85]:
# Sample data
x = [1, 2, 3, 4, 5, 3, 6]
y = [2, 4, 5, 4, 5, 7, 3]

# Mean of x and y
mean_x = np.mean(x)
mean_y = np.mean(y)

# Total number of observations
n = len(x)

# Using the formula to calculate the b1 and b0
numer = 0
denom = 0
for i in range(n):
    numer += (x[i] - mean_x) * (y[i] - mean_y)
    denom += (x[i] - mean_x) ** 2
b1 = numer / denom
b0 = mean_y - (b1 * mean_x)

# Print coefficients
print("b1 =", b1)
print("b0 =", b0)

b1 = 0.12096774193548386
b0 = 3.870967741935484


In [86]:
#broadcast in numpy

x = np.array([[1,2,3]])
y = np.array([[1],
              [2],
              [3]])

x+y

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [96]:
#matrix multiplication

np.matrix([[1,2,3],[4,5,6]]) * np.matrix([[1,2],
                                          [3,4],
                                          [5,6]]) 

matrix([[22, 28],
        [49, 64]])

- $Q = {q_1, q_2, ..., q_n}$ is the set of states
- $\Sigma = {a_1, a_2, ..., a_m}$ is the set of input symbols
- $q_0$ is the initial state
- $F = {f_1, f_2, ..., f_n}$ is the set of final or accepting states
- $\delta : Q \times \Sigma \rightarrow Q$ is the transition function, where $\delta(q_i, a_j) = q_k$ is the next state when the machine is in state $q_i$ and receives input symbol $a_j$