In [1]:
import numpy as np

In [30]:
A = np.random.randint(0, 10, (2,3))
v1 = np.array([1,1])

In [31]:
A, v1

(array([[4, 0, 8],
        [6, 3, 7]]),
 array([1, 1]))

In [33]:
A.T @ v1

array([10,  3, 15])

In [34]:
v1 @ A

array([10,  3, 15])