In [85]:
import warnings
warnings.filterwarnings('ignore')

In [86]:
import math
import statistics
import numpy as np
import scipy.stats
import pandas as pd
import matplotlib.pyplot as plt

In [87]:
A = np.array([[1,1,1],
              [2,3,1],
              [4,9,2],
              [8,27,4],
              [16,1,1]])

A1D = A.reshape(15)
np.shape(A)

(5, 3)

In [88]:
#default axis=None will calculate statistics for your entire dataset

(np.mean(A), np.median(A), A.var(ddof=1)) == (np.mean(A1D), np.median(A1D), A1D.var(ddof=1))

True

In [89]:
#axis=0 will return a list of calculated statistics. One for each column of your 2D array
#Since A is cointaining 3 columns so the list cointains 3 values

np.mean(A, axis=0), [np.mean(A1D[n::3]) for n in range(3)]

(array([6.2, 8.2, 1.8]), [6.2, 8.2, 1.8])

In [90]:
#check this out (extract each column of a 2D array)

[np.mean([A[i][j] for i in range(np.shape(A)[0])]) for j in range(np.shape(A)[1])] == np.mean(A,axis = 0)

array([ True,  True,  True])

In [91]:
#axis=1 will return a list  of calculated statistics. One for each row of your 2D array
#Since A is containing 5 rows so the list contains 5 values

np.mean(A, axis=1) ,[np.mean(A[n]) for n in range(np.shape(A)[0])]

(array([ 1.,  2.,  5., 13.,  6.]), [1.0, 2.0, 5.0, 13.0, 6.0])

In [92]:
np.median(A,axis=1), np.median(A,axis=0)

(array([1., 2., 4., 8., 1.]), array([4., 3., 1.]))

In [93]:
np.var(A,axis=1)

array([  0.        ,   0.66666667,   8.66666667, 100.66666667,
        50.        ])

In [94]:
np.var(A,axis=0)

array([29.76, 96.96,  1.36])

In [95]:
A

array([[ 1,  1,  1],
       [ 2,  3,  1],
       [ 4,  9,  2],
       [ 8, 27,  4],
       [16,  1,  1]])

In [96]:
np.std(A, axis=0)

array([5.45527268, 9.8468269 , 1.16619038])

In [97]:
np.std(A, axis=1)

array([ 0.        ,  0.81649658,  2.94392029, 10.03327796,  7.07106781])

In [98]:
#in scipy axis is working similarly, axis=0 by default

scipy.stats.gmean(A), scipy.stats.gmean(A, axis=None)

(array([4.        , 3.73719282, 1.51571657]), 2.829705017016332)

In [99]:
result = scipy.stats.describe(A,axis=None)
result.mean 

5.4

----

In [100]:
row_names = ['1st','2nd','3rd','4th','5th']
col_names = ['A','B','C']
df = pd.DataFrame(A,index=row_names,columns=col_names)

In [101]:
df

A   B  C
1st   1   1  1
2nd   2   3  1
3rd   4   9  2
4th   8  27  4
5th  16   1  1

In [102]:
#default df methods return statistics for each column as a Series object
df.mean(), type(df.mean())

(A    6.2
 B    8.2
 C    1.8
 dtype: float64,
 pandas.core.series.Series)

In [103]:
df.var()

A     37.2
B    121.2
C      1.7
dtype: float64

In [104]:
df.var(axis=1) #axis=1 will return a Series of statistics for each row

1st      0.0
2nd      1.0
3rd     13.0
4th    151.0
5th     75.0
dtype: float64

In [105]:
df['A'].mean(), df['A'].var() #statistics for one column

(6.2, 37.20000000000001)

In [106]:
B,C = df.values, df.to_numpy() #convert all values of Dataframe into np.ndarray
type(B),type(C)                #(get rid of row and col names)

(numpy.ndarray, numpy.ndarray)

In [107]:
df.describe()

A          B        C
count   5.00000   5.000000  5.00000
mean    6.20000   8.200000  1.80000
std     6.09918  11.009087  1.30384
min     1.00000   1.000000  1.00000
25%     2.00000   1.000000  1.00000
50%     4.00000   3.000000  1.00000
75%     8.00000   9.000000  2.00000
max    16.00000  27.000000  4.00000

In [108]:
type(df.describe())

pandas.core.frame.DataFrame

In [109]:
df.describe()['A']

count     5.00000
mean      6.20000
std       6.09918
min       1.00000
25%       2.00000
50%       4.00000
75%       8.00000
max      16.00000
Name: A, dtype: float64

In [110]:
df.describe()['A']['mean'], df.describe().at['mean','A']

(6.2, 6.2)