In [3]:
import numpy as np

In [4]:
A = np.random.randint(0, 10, (2,3))
v1 = np.array([1,2])
v2 = np.array([1,2])
v1_v2 = np.c_[v1,v2]

In [5]:
A, v1_v2

(array([[4, 4, 7],
        [6, 6, 2]]),
 array([[1, 1],
        [2, 2]]))

In [6]:
A.T @ v1_v2

array([[16, 16],
       [16, 16],
       [11, 11]])

In [7]:
v1_v2 @ A #transforming vectors v1 and v2 from 2d into 3d space using A

array([[10, 10,  9],
       [20, 20, 18]])