In [1]:
import numpy as np

In [8]:
A = np.random.randint(0, 10, (2,3))
v1 = np.array([1,1])
v2 = np.array([1,1])
v1_v2 = np.c_[v1,v2]

In [9]:
A, v1_v2

(array([[3, 2, 4],
        [2, 1, 2]]),
 array([[1, 1],
        [1, 1]]))

In [11]:
A.T @ v1_v2

array([[5, 5],
       [3, 3],
       [6, 6]])

In [14]:
v1_v2 @ A #transforming vectors v1 and v2 from 2d into 3d space using A

array([[5, 3, 6],
       [5, 3, 6]])